version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
configuration: ReleaseAndDeploy
platform: Any CPU
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  gkey:
    secure: 24L6ZxEROBbJxD03e/uYEg==
install:
- ps: >-
    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt Gorgon.enc -secret $env:gkey -out GorgonFull.snk
before_build:
- ps: .\ProjectSigner.exe GorgonFull.snk -y
build:
  project: Gorgon/Gorgon.sln
  parallel: true
  verbosity: normal
after_build:
- ps: >-
    $artifactDir = "Artifacts"

    $artifactBin = "$artifactDir\\Bin\\"

    $artifactPlugIns = "$artifactDir\\PlugIns\\"


    if (Test-Path $artifactDir)

    {
        rmdir $artifactDir -recurse
    }


    mkdir $artifactDir

    mkdir $artifactBin

    mkdir $artifactPlugIns


    $gorgonDllsXmls = (Get-ChildItem "Gorgon\\" -include *.dll, *.xml -Recurse | where { $_.FullName -notmatch "\\obj\\" -and $_.FullName -notmatch "\\debug\\"})

    $plugInDlls = (Get-ChildItem "PlugIns\\Bin\\" -include *.dll -Recurse | where { $_.FullName -notmatch "\\debug\\"})


    ForEach ($dll in $gorgonDllsXmls)

    {
        Copy-Item $dll.FullName $artifactBin
    }


    ForEach ($plugInDll in $plugInDlls)

    {
        Copy-Item $plugInDll.FullName $artifactPlugIns
    }
test: off
artifacts:
- path: Artifacts\
  name: Gorgon2.0
deploy: off