# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: 3.2.$(Rev:r).$(DayOfYear)

trigger:
  branches:
    include:
      - BugFixes

jobs:
  - job: 'BugFixes_Debug'
    pool:
      vmImage: 'windows-2022'

    variables:
      solution: 'Gorgon.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Debug'

    steps:
      - task: CmdLine@2
        displayName: 'Updating version to $(Build.BuildNumber)'
        inputs:
          script: 'CsProjVersionUpdater.exe $(Build.BuildNumber)'

      - task: NuGetToolInstaller@1
        inputs:
          checkLatest: true

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
