//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgon.IO.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorgon.IO.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The root directory cannot be moved..
    /// </summary>
    internal static string GORFS_ERR_CANNOT_MOVE_ROOT {
        get {
            return ResourceManager.GetString("GORFS_ERR_CANNOT_MOVE_ROOT", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The directory &apos;{0}&apos; is an ancestor of &apos;{1}&apos; and cannot be moved to &apos;{1}&apos;..
    /// </summary>
    internal static string GORFS_ERR_CANNOT_MOVE_TO_CHILD {
        get {
            return ResourceManager.GetString("GORFS_ERR_CANNOT_MOVE_TO_CHILD", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The file system &apos;{0}&apos; could not be read by any of the available providers..
    /// </summary>
    internal static string GORFS_ERR_CANNOT_READ_FILESYSTEM {
        get {
            return ResourceManager.GetString("GORFS_ERR_CANNOT_READ_FILESYSTEM", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to A directory with the path &apos;{0}&apos; already exists..
    /// </summary>
    internal static string GORFS_ERR_DIRECTORY_EXISTS {
        get {
            return ResourceManager.GetString("GORFS_ERR_DIRECTORY_EXISTS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist..
    /// </summary>
    internal static string GORFS_ERR_DIRECTORY_NOT_FOUND {
        get {
            return ResourceManager.GetString("GORFS_ERR_DIRECTORY_NOT_FOUND", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to A file with the path &apos;{0}&apos; already exists..
    /// </summary>
    internal static string GORFS_ERR_FILE_EXISTS {
        get {
            return ResourceManager.GetString("GORFS_ERR_FILE_EXISTS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist..
    /// </summary>
    internal static string GORFS_ERR_FILE_NOT_FOUND {
        get {
            return ResourceManager.GetString("GORFS_ERR_FILE_NOT_FOUND", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The path &apos;{0}&apos; is not legal..
    /// </summary>
    internal static string GORFS_ERR_ILLEGAL_PATH {
        get {
            return ResourceManager.GetString("GORFS_ERR_ILLEGAL_PATH", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The mount point &apos;{0}&apos; with physical location &apos;{1}&apos; was not found..
    /// </summary>
    internal static string GORFS_ERR_MOUNTPOINT_NOT_FOUND {
        get {
            return ResourceManager.GetString("GORFS_ERR_MOUNTPOINT_NOT_FOUND", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The path &apos;{0}&apos; does not contain a file name..
    /// </summary>
    internal static string GORFS_ERR_NO_FILENAME {
        get {
            return ResourceManager.GetString("GORFS_ERR_NO_FILENAME", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The file system provider plug in &apos;{0}&apos; was not found..
    /// </summary>
    internal static string GORFS_ERR_NO_PROVIDER_PLUGIN {
        get {
            return ResourceManager.GetString("GORFS_ERR_NO_PROVIDER_PLUGIN", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The path &apos;{0}&apos; is not valid..
    /// </summary>
    internal static string GORFS_ERR_PATH_INVALID {
        get {
            return ResourceManager.GetString("GORFS_ERR_PATH_INVALID", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to A provider to mount a physical directory as a file system..
    /// </summary>
    internal static string GORFS_FOLDER_FS_DESC {
        get {
            return ResourceManager.GetString("GORFS_FOLDER_FS_DESC", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to A file system writer that stores directories and file data in an operating system directory..
    /// </summary>
    internal static string GORFS_FOLDER_WRITER_FS_DESC {
        get {
            return ResourceManager.GetString("GORFS_FOLDER_WRITER_FS_DESC", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Mount Point Virtual Location: {0}, Physical Location: {1}.
    /// </summary>
    internal static string GORFS_TOSTR_MOUNTPOINT {
        get {
            return ResourceManager.GetString("GORFS_TOSTR_MOUNTPOINT", resourceCulture);
        }
    }
}
