//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgon.Graphics.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorgon.Graphics.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource assigned to this barrier has been disposed..
        /// </summary>
        internal static string GORGFX_ERR_BARRIER_RESOURCE_DISPOSED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BARRIER_RESOURCE_DISPOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call the Begin method prior to calling this method..
        /// </summary>
        internal static string GORGFX_ERR_BATCH_NOT_STARTED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BATCH_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch is already in progress..
        /// </summary>
        internal static string GORGFX_ERR_BATCH_STARTED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BATCH_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer &apos;{0}&apos; must not have a usage of download. .
        /// </summary>
        internal static string GORGFX_ERR_BUFFER_CANNOT_BE_DOWNLOAD {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BUFFER_CANNOT_BE_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is too large..
        /// </summary>
        internal static string GORGFX_ERR_BUFFER_OFFSET_OVERRUN {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BUFFER_OFFSET_OVERRUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset {0} plus the size {1} exceeds the total size of the buffer: {2}..
        /// </summary>
        internal static string GORGFX_ERR_BUFFER_OVERRUN {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BUFFER_OVERRUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the buffer &apos;{0}&apos; is too small. Must be equal to or larger than {1} byte(s)..
        /// </summary>
        internal static string GORGFX_ERR_BUFFER_TOO_SMALL {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BUFFER_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer is {0} bytes in size. A single element is {1} bytes in size. This buffer is too small to hold a single element..
        /// </summary>
        internal static string GORGFX_ERR_BUFFER_TOO_SMALL_FOR_STRUCTURE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BUFFER_TOO_SMALL_FOR_STRUCTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer &apos;{0}&apos; is too small ({1} bytes) to accommodate the minimum size for a {2} ({3} bytes)..
        /// </summary>
        internal static string GORGFX_ERR_BUFFER_TOO_SMALL_FOR_VIEW {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BUFFER_TOO_SMALL_FOR_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer &apos;{0}&apos; does not have a usage of Download. Only buffers with a usage value of Download may be read by the CPU..
        /// </summary>
        internal static string GORGFX_ERR_BUFFER_USAGE_NOT_DOWNLOAD {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BUFFER_USAGE_NOT_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer usage {0} is not valid for buffer &apos;{1}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_BUFFER_USAGE_UNKNOWN {
            get {
                return ResourceManager.GetString("GORGFX_ERR_BUFFER_USAGE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method cannot be called while a frame is actively being rendered. 
        ///
        ///Call EndFrame() prior to calling this method, or call it prior to BeginFrame()..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CALL_ON_ACTIVE_FRAME {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CALL_ON_ACTIVE_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error closing the command list &apos;{0}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CLOSE_COMMAND_LIST {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CLOSE_COMMAND_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error compiling the {0} shader..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_COMPILE_SHADER {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_COMPILE_SHADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The texture &apos;{0}&apos; is a depth/stencil texture. Images cannot be copied into a depth/stencil texture..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_COPY_IMAGE_TO_DEPTH_STENCIL {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_COPY_IMAGE_TO_DEPTH_STENCIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The texture &apos;{0}&apos; has a multi sample value of {1}. Only textures without multi sampling can receive image data..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_COPY_IMAGE_TO_MULTISAMPLE_TEXTURE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_COPY_IMAGE_TO_MULTISAMPLE_TEXTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy the source texture &apos;{0}&apos; into itself with the same sub resource index ({1}).
        ///
        ///The sub resources must be different if copying into the same texture..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_COPY_TEXTURE_INTO_ITSELF {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_COPY_TEXTURE_INTO_ITSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source texture &apos;{0}&apos; dimensions, format group, mip-map count, or array count does not match that of the destination texture &apos;{1}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_COPY_TEXTURE_NOT_SAME {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_COPY_TEXTURE_NOT_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy the image data to the texture.
        ///
        ///The format of the image {0} and the format of the texture {1} are incompatible, and cannot be converted..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_COPY_WITH_IMAGE_FORMAT {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_COPY_WITH_IMAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the video adapter interface for adapter index {0}..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_ADAPTER {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_ADAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a memory allocator for adapter {0}..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_ALLOCATOR {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_ALLOCATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a command allocator..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_COMMAND_ALLOCATOR {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_COMMAND_ALLOCATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a command list of type &apos;{0}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_COMMAND_LIST {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_COMMAND_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating a command queue of type {0}..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_COMMAND_QUEUE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_COMMAND_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a Direct3D 12 device object for adapter {0}..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_D3D12_DEVICE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_D3D12_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the descriptor heap for &apos;{0}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_DESCRIPTOR_HEAP {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_DESCRIPTOR_HEAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating an instance of the shader compiler..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_DXCOMPILER {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_DXCOMPILER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a DXGI factory..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_FACTORY {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_FACTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the fence object..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_FENCE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_FENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create the heap {0}..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_HEAP {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_HEAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the resource..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_RESOURCE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the swap chain &apos;{0}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_SWAPCHAIN {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_SWAPCHAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a valid texture type..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_TEXTURE_UNKNOWN_TYPE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_TEXTURE_UNKNOWN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a valid view type for the resource..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_CREATE_VIEW_UNKNOWN_TYPE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_CREATE_VIEW_UNKNOWN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enumerate feature data for the adapter &apos;{0}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_ENUMERATE_GPU {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_ENUMERATE_GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize the fence value..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_INIT_FENCE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_INIT_FENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the dxcompiler.dll file..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_LOAD_DXCOMPILERDLL {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_LOAD_DXCOMPILERDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while resetting the command allocator..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_RESET_CMD_ALLOCATOR {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_RESET_CMD_ALLOCATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error resetting the command list..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_RESET_COMMAND_LIST {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_RESET_COMMAND_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while resizing the swap chain &apos;{0}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_RESIZE_SWAPCHAIN {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_RESIZE_SWAPCHAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the back buffer resource at index {0} for the swap chain &apos;{1}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_RETRIEVE_BACKBUFFER {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_RETRIEVE_BACKBUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the shader compilation errors..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_RETRIEVE_SHADER_COMPILATION_ERRORS {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_RETRIEVE_SHADER_COMPILATION_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set the full screen mode. The containing output on the adapter &apos;{0}&apos; could not be determined..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_SET_FULLSCREEN {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_SET_FULLSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error switching the screen mode on adapter &apos;{0}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_SET_SCREEN_MODE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_SET_SCREEN_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error writing the data to &apos;{0}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_WRITE_DATA {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_WRITE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer &apos;{0}&apos; has a usage of Download. Only buffers with a usage of Default, Upload or DynamicPerFrame can be written to..
        /// </summary>
        internal static string GORGFX_ERR_CANNOT_WRITE_TO_DOWNLOAD_BUFFER {
            get {
                return ResourceManager.GetString("GORGFX_ERR_CANNOT_WRITE_TO_DOWNLOAD_BUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command list &apos;{0}&apos; has already been submitted for execution..
        /// </summary>
        internal static string GORGFX_ERR_COMMAND_LIST_ALREADY_SUBMITTED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_COMMAND_LIST_ALREADY_SUBMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command list was still open for recording at the beginning of the frame.
        ///
        ///Please ensure all command lists have been submitted for execution at the end of the frame..
        /// </summary>
        internal static string GORGFX_ERR_COMMAND_LIST_STILL_OPEN {
            get {
                return ResourceManager.GetString("GORGFX_ERR_COMMAND_LIST_STILL_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the {0} command queue..
        /// </summary>
        internal static string GORGFX_ERR_COMMAND_QUEUE_CREATE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_COMMAND_QUEUE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The depth stencil texture &apos;{0}&apos; cannot be copied unless the entire sub resource is copied. This means the destination coordinates must be 0, and the source region must be empty..
        /// </summary>
        internal static string GORGFX_ERR_DEPTH_STENCIL_CANNOT_BE_COPIED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_DEPTH_STENCIL_CANNOT_BE_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory in the {0} descriptor heap..
        /// </summary>
        internal static string GORGFX_ERR_DESCRIPTORHEAP_OUT_OF_MEMORY {
            get {
                return ResourceManager.GetString("GORGFX_ERR_DESCRIPTORHEAP_OUT_OF_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device was removed..
        /// </summary>
        internal static string GORGFX_ERR_DEVICE_REMOVED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_DEVICE_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer &apos;{0}&apos; cannot be used as a copy destination because it has a usage of DynamicPerFrame. .
        /// </summary>
        internal static string GORGFX_ERR_DYNAMIC_BUFFER_CANNOT_BE_DESTINATION {
            get {
                return ResourceManager.GetString("GORGFX_ERR_DYNAMIC_BUFFER_CANNOT_BE_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was not found..
        /// </summary>
        internal static string GORGFX_ERR_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("GORGFX_ERR_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format {0} is an invalid display format..
        /// </summary>
        internal static string GORGFX_ERR_FORMAT_INVALID_DISPLAY_FORMAT {
            get {
                return ResourceManager.GetString("GORGFX_ERR_FORMAT_INVALID_DISPLAY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frame has already started rendering..
        /// </summary>
        internal static string GORGFX_ERR_FRAME_ALREADY_STARTED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_FRAME_ALREADY_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frame has not started rendering yet. Did you forget to call BeginFrame()?.
        /// </summary>
        internal static string GORGFX_ERR_FRAME_NOT_STARTED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_FRAME_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index {0} is not on the heap..
        /// </summary>
        internal static string GORGFX_ERR_HEAP_INDEX_NOT_FOUND {
            get {
                return ResourceManager.GetString("GORGFX_ERR_HEAP_INDEX_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heap &apos;{0}&apos; is out of memory (size: {1})..
        /// </summary>
        internal static string GORGFX_ERR_HEAP_OUT_OF_MEMORY {
            get {
                return ResourceManager.GetString("GORGFX_ERR_HEAP_OUT_OF_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heap type &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string GORGFX_ERR_HEAP_TYPE_INVALID {
            get {
                return ResourceManager.GetString("GORGFX_ERR_HEAP_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height {0} is too small, it must be at least {1}..
        /// </summary>
        internal static string GORGFX_ERR_HEIGHT_TOO_SMALL {
            get {
                return ResourceManager.GetString("GORGFX_ERR_HEIGHT_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index {0} is too large. The maximum value is {1}..
        /// </summary>
        internal static string GORGFX_ERR_INDEX_TOO_LARGE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_INDEX_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alignment {0} is not valid. The alignment must be a positive integer value..
        /// </summary>
        internal static string GORGFX_ERR_INVALID_ALIGNMENT {
            get {
                return ResourceManager.GetString("GORGFX_ERR_INVALID_ALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primitive type {0} is not valid for this method..
        /// </summary>
        internal static string GORGFX_ERR_INVALID_PRIMITIVE_TYPE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_INVALID_PRIMITIVE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format {0} is not a valid render target format..
        /// </summary>
        internal static string GORGFX_ERR_INVALID_RENDER_TARGET_FORMAT {
            get {
                return ResourceManager.GetString("GORGFX_ERR_INVALID_RENDER_TARGET_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The struct size must be a multiple of 16, and a minimum of 16 bytes..
        /// </summary>
        internal static string GORGFX_ERR_INVALID_STRUCT_SIZE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_INVALID_STRUCT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The usage of &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string GORGFX_ERR_INVALID_USAGE {
            get {
                return ResourceManager.GetString("GORGFX_ERR_INVALID_USAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the Agility SDK..
        /// </summary>
        internal static string GORGFX_ERR_LOAD_AGILITY_FAILED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_LOAD_AGILITY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The texture &apos;{0}&apos; has a multi sample value of {1} and cannot be copied unless the entire sub resource is copied. This means the destination coordinates must be 0, and the source region must be empty..
        /// </summary>
        internal static string GORGFX_ERR_MULTISAMPLE_CANNOT_BE_COPIED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_MULTISAMPLE_CANNOT_BE_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The multi sample settings ({0}) for the texture &apos;{1}&apos; is not the same as the multi sample settings ({2}) for the texture &apos;{3}&apos;..
        /// </summary>
        internal static string GORGFX_ERR_MULTISAMPLE_SOURCE_DEST_DIFFERENT {
            get {
                return ResourceManager.GetString("GORGFX_ERR_MULTISAMPLE_SOURCE_DEST_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable video adapter could be found on the system.  Gorgon requires a Direct 3D 12 capable video adapter..
        /// </summary>
        internal static string GORGFX_ERR_NO_SUITABLE_ADAPTER {
            get {
                return ResourceManager.GetString("GORGFX_ERR_NO_SUITABLE_ADAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer &apos;{0}&apos; does not support constant data..
        /// </summary>
        internal static string GORGFX_ERR_NOT_CONSTANT_BUFFER {
            get {
                return ResourceManager.GetString("GORGFX_ERR_NOT_CONSTANT_BUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPU address for &apos;{0}&apos; is NULL..
        /// </summary>
        internal static string GORGFX_ERR_NULL_GPU_ADDRESS {
            get {
                return ResourceManager.GetString("GORGFX_ERR_NULL_GPU_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer {0} cannot be a render target. Render targets require a buffer with a Default usage..
        /// </summary>
        internal static string GORGFX_ERR_RTV_BUFFER_NOT_DEFAULT {
            get {
                return ResourceManager.GetString("GORGFX_ERR_RTV_BUFFER_NOT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors were found:
        ///
        ///{0}.
        /// </summary>
        internal static string GORGFX_ERR_SHADER_COMPILE_ERROR {
            get {
                return ResourceManager.GetString("GORGFX_ERR_SHADER_COMPILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shader file is corrupt. .
        /// </summary>
        internal static string GORGFX_ERR_SHADER_FILE_CORRUPT {
            get {
                return ResourceManager.GetString("GORGFX_ERR_SHADER_FILE_CORRUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The include file in line &apos;{0}&apos; was not found in the include list..
        /// </summary>
        internal static string GORGFX_ERR_SHADER_INCLUDE_NOT_FOUND {
            get {
                return ResourceManager.GetString("GORGFX_ERR_SHADER_INCLUDE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The include line &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string GORGFX_ERR_SHADER_INCLUDE_PATH_INVALID {
            get {
                return ResourceManager.GetString("GORGFX_ERR_SHADER_INCLUDE_PATH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shader model version {0} is not supported..
        /// </summary>
        internal static string GORGFX_ERR_SHADER_MODEL_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_SHADER_MODEL_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shader type {0} is not supported..
        /// </summary>
        internal static string GORGFX_ERR_SHADER_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_SHADER_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The steam is not seekable..
        /// </summary>
        internal static string GORGFX_ERR_STREAM_CANNOT_SEEK {
            get {
                return ResourceManager.GetString("GORGFX_ERR_STREAM_CANNOT_SEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is read only..
        /// </summary>
        internal static string GORGFX_ERR_STREAM_IS_READONLY {
            get {
                return ResourceManager.GetString("GORGFX_ERR_STREAM_IS_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is write only..
        /// </summary>
        internal static string GORGFX_ERR_STREAM_IS_WRITEONLY {
            get {
                return ResourceManager.GetString("GORGFX_ERR_STREAM_IS_WRITEONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The swap chain &apos;{0}&apos; returned an invalid wait handle..
        /// </summary>
        internal static string GORGFX_ERR_SWAPCHAIN_WAIT_HANDLE_INVALID {
            get {
                return ResourceManager.GetString("GORGFX_ERR_SWAPCHAIN_WAIT_HANDLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source texture &apos;{0}&apos; has a format group of {1}, and the destination texture &apos;{2}&apos; has a format group of {3}. 
        ///
        ///The texture formats must belong to the same grouping in order to copy them..
        /// </summary>
        internal static string GORGFX_ERR_TEXTURE_COPY_FORMAT_GROUPS_DIFFERENT {
            get {
                return ResourceManager.GetString("GORGFX_ERR_TEXTURE_COPY_FORMAT_GROUPS_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertex stride for buffer &apos;{0}&apos; must be at least 1 byte..
        /// </summary>
        internal static string GORGFX_ERR_VERTEX_STRIDE_TOO_SMALL {
            get {
                return ResourceManager.GetString("GORGFX_ERR_VERTEX_STRIDE_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} failed to wait for the {1}..
        /// </summary>
        internal static string GORGFX_ERR_WAIT_FAILED {
            get {
                return ResourceManager.GetString("GORGFX_ERR_WAIT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width {0} is too small, it must be at least {1}..
        /// </summary>
        internal static string GORGFX_ERR_WIDTH_TOO_SMALL {
            get {
                return ResourceManager.GetString("GORGFX_ERR_WIDTH_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window handle must not be NULL..
        /// </summary>
        internal static string GORGFX_NULL_WINDOW_HANDLE {
            get {
                return ResourceManager.GetString("GORGFX_NULL_WINDOW_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Adapter.
        /// </summary>
        internal static string GORGFX_STR_ADAPTER {
            get {
                return ResourceManager.GetString("GORGFX_STR_ADAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string GORGFX_STR_MEM_TYPE_LOCAL {
            get {
                return ResourceManager.GetString("GORGFX_STR_MEM_TYPE_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-local.
        /// </summary>
        internal static string GORGFX_STR_MEM_TYPE_NON_LOCAL {
            get {
                return ResourceManager.GetString("GORGFX_STR_MEM_TYPE_NON_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string GORGFX_STR_OUTPUT {
            get {
                return ResourceManager.GetString("GORGFX_STR_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Mode - {0}x{1} {2} Refresh Rate: {3:#####0.0}Hz.
        /// </summary>
        internal static string GORGFX_STR_VIDEO_MODE {
            get {
                return ResourceManager.GetString("GORGFX_STR_VIDEO_MODE", resourceCulture);
            }
        }
    }
}
