
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'Form' contains field '_blurEffect' that is of IDisposable type 'Gorgon2DGaussBlurEffect', but it is never disposed. Change the Dispose method on 'Form' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.Form._blurEffect")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'Form' contains field '_fontFactory' that is of IDisposable type 'GorgonFontFactory', but it is never disposed. Change the Dispose method on 'Form' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.Form._fontFactory")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'Form' contains field '_graphics' that is of IDisposable type 'GorgonGraphics', but it is never disposed. Change the Dispose method on 'Form' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.Form._graphics")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'Form' contains field '_helpFont' that is of IDisposable type 'GorgonFont', but it is never disposed. Change the Dispose method on 'Form' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.Form._helpFont")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'Form' contains field '_renderer' that is of IDisposable type 'Gorgon2D', but it is never disposed. Change the Dispose method on 'Form' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.Form._renderer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'Form' contains field '_screen' that is of IDisposable type 'GorgonSwapChain', but it is never disposed. Change the Dispose method on 'Form' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.Form._screen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'Form' contains field '_textFont' that is of IDisposable type 'GorgonFont', but it is never disposed. Change the Dispose method on 'Form' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.Form._textFont")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'OnLoad' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.Form.OnLoad(System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Main' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.Program.Main")]