//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgon.Editor.ImageAtlasTool.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorgon.Editor.ImageAtlasTool.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap calculate_22x22 {
        get {
            object obj = ResourceManager.GetObject("calculate_22x22", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap folder_20x20 {
        get {
            object obj = ResourceManager.GetObject("folder_20x20", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Output folder.
    /// </summary>
    internal static string GORIAG_CAPTION_FOLDER_SELECT {
        get {
            return ResourceManager.GetString("GORIAG_CAPTION_FOLDER_SELECT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Generating the texture atlas will overwrite one or more textures.
    ///
    ///Are you sure you want to do this?.
    /// </summary>
    internal static string GORIAG_CONFIRM_OVERWRITE {
        get {
            return ResourceManager.GetString("GORIAG_CONFIRM_OVERWRITE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to A tool for generating a texture atlas from a series of individual images.
    ///
    ///This tool will also, optionally, generate sprites from the resulting texture atlas..
    /// </summary>
    internal static string GORIAG_DESC_BUTTON {
        get {
            return ResourceManager.GetString("GORIAG_DESC_BUTTON", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select a folder to save the atlas image(s) into..
    /// </summary>
    internal static string GORIAG_DESC_FOLDER_SELECT {
        get {
            return ResourceManager.GetString("GORIAG_DESC_FOLDER_SELECT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error while calculating the texture dimensions.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIAG_ERR_CALC {
        get {
            return ResourceManager.GetString("GORIAG_ERR_CALC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The calculated size would be too large for this video adapter to handle..
    /// </summary>
    internal static string GORIAG_ERR_CALC_TOO_LARGE {
        get {
            return ResourceManager.GetString("GORIAG_ERR_CALC_TOO_LARGE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error browsing the file system folders.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIAG_ERR_FOLDER_SELECT {
        get {
            return ResourceManager.GetString("GORIAG_ERR_FOLDER_SELECT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error while generating the atlas.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIAG_ERR_GEN_ATLAS {
        get {
            return ResourceManager.GetString("GORIAG_ERR_GEN_ATLAS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cannot write the image file &apos;{0}&apos; because it is already open in the editor..
    /// </summary>
    internal static string GORIAG_ERR_IMAGE_OPEN {
        get {
            return ResourceManager.GetString("GORIAG_ERR_IMAGE_OPEN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error launching the image atlas generation tool.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIAG_ERR_LAUNCH {
        get {
            return ResourceManager.GetString("GORIAG_ERR_LAUNCH", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error loading the selected images.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIAG_ERR_LOAD_IMAGES {
        get {
            return ResourceManager.GetString("GORIAG_ERR_LOAD_IMAGES", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was not enough room for one or more of the image.
    ///
    ///Please increase the image size, and/or array count, or reduce the padding and try again..
    /// </summary>
    internal static string GORIAG_ERR_NO_ROOM {
        get {
            return ResourceManager.GetString("GORIAG_ERR_NO_ROOM", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error while changing the array or texture index.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIAG_ERR_PREVIEW_ARRAY {
        get {
            return ResourceManager.GetString("GORIAG_ERR_PREVIEW_ARRAY", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error while attempting to save the image atlas.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIAG_ERR_SAVE {
        get {
            return ResourceManager.GetString("GORIAG_ERR_SAVE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error searching through the images.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIAG_ERR_SEARCH {
        get {
            return ResourceManager.GetString("GORIAG_ERR_SEARCH", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cannot update the sprite file &apos;{0}&apos; because it is already open in the editor..
    /// </summary>
    internal static string GORIAG_ERR_SPRITE_OPEN {
        get {
            return ResourceManager.GetString("GORIAG_ERR_SPRITE_OPEN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Images.
    /// </summary>
    internal static string GORIAG_GROUP_BUTTON {
        get {
            return ResourceManager.GetString("GORIAG_GROUP_BUTTON", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Gorgon Image Atlas.
    /// </summary>
    internal static string GORIAG_PLUGIN_DESC {
        get {
            return ResourceManager.GetString("GORIAG_PLUGIN_DESC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Array index {0}/{1}.
    /// </summary>
    internal static string GORIAG_TEXT_ARRAY_COUNT {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_ARRAY_COUNT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Array index {0}/{1}, Image {2}/{3}.
    /// </summary>
    internal static string GORIAG_TEXT_ARRAY_TEXTURE_COUNT {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_ARRAY_TEXTURE_COUNT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Image Atlas.
    /// </summary>
    internal static string GORIAG_TEXT_BUTTON {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_BUTTON", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} images loaded..
    /// </summary>
    internal static string GORIAG_TEXT_IMAGE_COUNT {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_IMAGE_COUNT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Loading....
    /// </summary>
    internal static string GORIAG_TEXT_LOADING {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_LOADING", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Loading image &apos;{0}&apos;....
    /// </summary>
    internal static string GORIAG_TEXT_LOADING_IMAGE {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_LOADING_IMAGE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Click the &quot;Generate Atlas&quot; button to create an atlas..
    /// </summary>
    internal static string GORIAG_TEXT_NO_ATLAS {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_NO_ATLAS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to No images loaded..
    /// </summary>
    internal static string GORIAG_TEXT_NO_IMAGES {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_NO_IMAGES", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select an image..
    /// </summary>
    internal static string GORIAG_TEXT_SELECT_IMAGE {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_SELECT_IMAGE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Image {0}/{1}.
    /// </summary>
    internal static string GORIAG_TEXT_TEXTURE_COUNT {
        get {
            return ResourceManager.GetString("GORIAG_TEXT_TEXTURE_COUNT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap imageatlas_16x16 {
        get {
            object obj = ResourceManager.GetObject("imageatlas_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap imageatlas_48x48 {
        get {
            object obj = ResourceManager.GetObject("imageatlas_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap info_16x16 {
        get {
            object obj = ResourceManager.GetObject("info_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap left_16x16 {
        get {
            object obj = ResourceManager.GetObject("left_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap load_image_48x48 {
        get {
            object obj = ResourceManager.GetObject("load_image_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap load_sprites_20x20 {
        get {
            object obj = ResourceManager.GetObject("load_sprites_20x20", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap load_sprites_48x48 {
        get {
            object obj = ResourceManager.GetObject("load_sprites_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap right_16x16 {
        get {
            object obj = ResourceManager.GetObject("right_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap White_2x2 {
        get {
            object obj = ResourceManager.GetObject("White_2x2", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
