//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgon.Editor.ImageSplitTool.Properties {
    using System;
    
    
    // Comment stripped.
    // Comment stripped.
    // Comment stripped.
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorgon.Editor.ImageSplitTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap folder_20x20 {
            get {
                object obj = ResourceManager.GetObject("folder_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_CAPTION_FOLDER_SELECT {
            get {
                return ResourceManager.GetString("GORIST_CAPTION_FOLDER_SELECT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_CONFIRM_CLOSE {
            get {
                return ResourceManager.GetString("GORIST_CONFIRM_CLOSE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_CONFIRM_FILE_EXISTS {
            get {
                return ResourceManager.GetString("GORIST_CONFIRM_FILE_EXISTS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_DESC_BUTTON {
            get {
                return ResourceManager.GetString("GORIST_DESC_BUTTON", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_DESC_FOLDER_SELECT {
            get {
                return ResourceManager.GetString("GORIST_DESC_FOLDER_SELECT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_ERR_CANNOT_ACCESS_FILESYSTEM_LOCK {
            get {
                return ResourceManager.GetString("GORIST_ERR_CANNOT_ACCESS_FILESYSTEM_LOCK", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_ERR_FOLDER_SELECT {
            get {
                return ResourceManager.GetString("GORIST_ERR_FOLDER_SELECT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_ERR_LAUNCH {
            get {
                return ResourceManager.GetString("GORIST_ERR_LAUNCH", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_ERR_SAVE {
            get {
                return ResourceManager.GetString("GORIST_ERR_SAVE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_ERR_SEARCH {
            get {
                return ResourceManager.GetString("GORIST_ERR_SEARCH", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_ERR_SPLIT {
            get {
                return ResourceManager.GetString("GORIST_ERR_SPLIT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_GROUP_BUTTON {
            get {
                return ResourceManager.GetString("GORIST_GROUP_BUTTON", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_PLUGIN_DESC {
            get {
                return ResourceManager.GetString("GORIST_PLUGIN_DESC", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_TEXT_BUTTON {
            get {
                return ResourceManager.GetString("GORIST_TEXT_BUTTON", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_TEXT_LOADING {
            get {
                return ResourceManager.GetString("GORIST_TEXT_LOADING", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_TEXT_PROCESSING {
            get {
                return ResourceManager.GetString("GORIST_TEXT_PROCESSING", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIST_TEXT_SELECT_IMAGE {
            get {
                return ResourceManager.GetString("GORIST_TEXT_SELECT_IMAGE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap image_split_16x16 {
            get {
                object obj = ResourceManager.GetObject("image_split_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap image_split_48x48 {
            get {
                object obj = ResourceManager.GetObject("image_split_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap Transparency_Pattern {
            get {
                object obj = ResourceManager.GetObject("Transparency_Pattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
