//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgon.Editor.ImageEditor.Properties {
    using System;
    
    
    // Comment stripped.
    // Comment stripped.
    // Comment stripped.
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorgon.Editor.ImageEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap add_plugin_22x22 {
            get {
                object obj = ResourceManager.GetObject("add_plugin_22x22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap alpha_16x16 {
            get {
                object obj = ResourceManager.GetObject("alpha_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap alpha_48x48 {
            get {
                object obj = ResourceManager.GetObject("alpha_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap burn_16x16 {
            get {
                object obj = ResourceManager.GetObject("burn_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap burn_48x48 {
            get {
                object obj = ResourceManager.GetObject("burn_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap cancel_16x16 {
            get {
                object obj = ResourceManager.GetObject("cancel_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap cancel_48x48 {
            get {
                object obj = ResourceManager.GetObject("cancel_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap confirm_16x16 {
            get {
                object obj = ResourceManager.GetObject("confirm_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap confirm_48x48 {
            get {
                object obj = ResourceManager.GetObject("confirm_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap dodge_16x16 {
            get {
                object obj = ResourceManager.GetObject("dodge_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap dodge_48x48 {
            get {
                object obj = ResourceManager.GetObject("dodge_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap edge_detect_16x16 {
            get {
                object obj = ResourceManager.GetObject("edge_detect_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap edge_detect_48x48 {
            get {
                object obj = ResourceManager.GetObject("edge_detect_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap edit_image_16x16 {
            get {
                object obj = ResourceManager.GetObject("edit_image_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap edit_image_48x48 {
            get {
                object obj = ResourceManager.GetObject("edit_image_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap emboss_16x16 {
            get {
                object obj = ResourceManager.GetObject("emboss_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap emboss_48x48 {
            get {
                object obj = ResourceManager.GetObject("emboss_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap export_image_16x16 {
            get {
                object obj = ResourceManager.GetObject("export_image_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap export_image_48x48 {
            get {
                object obj = ResourceManager.GetObject("export_image_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap gauss_blur_16x16 {
            get {
                object obj = ResourceManager.GetObject("gauss_blur_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap gauss_blur_48x48 {
            get {
                object obj = ResourceManager.GetObject("gauss_blur_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap generate_mip_maps_16x16 {
            get {
                object obj = ResourceManager.GetObject("generate_mip_maps_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap generate_mip_maps_48x48 {
            get {
                object obj = ResourceManager.GetObject("generate_mip_maps_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CAPTION_EXPORT_IMAGE {
            get {
                return ResourceManager.GetString("GORIMG_CAPTION_EXPORT_IMAGE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CAPTION_IMG_PICKER {
            get {
                return ResourceManager.GetString("GORIMG_CAPTION_IMG_PICKER", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CAPTION_IMPORT_IMAGE {
            get {
                return ResourceManager.GetString("GORIMG_CAPTION_IMPORT_IMAGE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CAPTION_SELECT_CODEC_DLL {
            get {
                return ResourceManager.GetString("GORIMG_CAPTION_SELECT_CODEC_DLL", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CONFIRM_3D_TO_2D {
            get {
                return ResourceManager.GetString("GORIMG_CONFIRM_3D_TO_2D", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CONFIRM_ARRAY_TO_VOLUME {
            get {
                return ResourceManager.GetString("GORIMG_CONFIRM_ARRAY_TO_VOLUME", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CONFIRM_CLOSE {
            get {
                return ResourceManager.GetString("GORIMG_CONFIRM_CLOSE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CONFIRM_EXPORT_LIMITS {
            get {
                return ResourceManager.GetString("GORIMG_CONFIRM_EXPORT_LIMITS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CONFIRM_GEN_MIPMAP {
            get {
                return ResourceManager.GetString("GORIMG_CONFIRM_GEN_MIPMAP", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CONFIRM_OVERWRITE_ARRAY_INDEX {
            get {
                return ResourceManager.GetString("GORIMG_CONFIRM_OVERWRITE_ARRAY_INDEX", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CONFIRM_OVERWRITE_DEPTH_SLICE {
            get {
                return ResourceManager.GetString("GORIMG_CONFIRM_OVERWRITE_DEPTH_SLICE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CONFIRM_REMOVE_CODECS {
            get {
                return ResourceManager.GetString("GORIMG_CONFIRM_REMOVE_CODECS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CONTENT_TYPE {
            get {
                return ResourceManager.GetString("GORIMG_CONTENT_TYPE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_CROP_LOSE_DATA {
            get {
                return ResourceManager.GetString("GORIMG_CROP_LOSE_DATA", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_DESC {
            get {
                return ResourceManager.GetString("GORIMG_DESC", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_DESC_UNDO_PREMULTIPLY {
            get {
                return ResourceManager.GetString("GORIMG_DESC_UNDO_PREMULTIPLY", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_APPLYING_EFFECTS {
            get {
                return ResourceManager.GetString("GORIMG_ERR_APPLYING_EFFECTS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CANNOT_COMPRESS {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CANNOT_COMPRESS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CANNOT_CONVERT {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CANNOT_CONVERT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CANNOT_OPEN_IMG_PICKER {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CANNOT_OPEN_IMG_PICKER", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CHANGE_TYPE {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CHANGE_TYPE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CODEC_ALREADY_LOADED {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CODEC_ALREADY_LOADED", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CODEC_ASSIGN {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CODEC_ASSIGN", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CODEC_LOAD_ERRORS_PRESENT {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CODEC_LOAD_ERRORS_PRESENT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CODEC_LOAD_FAIL {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CODEC_LOAD_FAIL", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CODEC_PLUGIN_ALREADY_LOADED {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CODEC_PLUGIN_ALREADY_LOADED", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_COMPRESSED_FILE {
            get {
                return ResourceManager.GetString("GORIMG_ERR_COMPRESSED_FILE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_COMPRESSED_RESIZE_MULTIPLE_4 {
            get {
                return ResourceManager.GetString("GORIMG_ERR_COMPRESSED_RESIZE_MULTIPLE_4", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_CONVERT_FORMAT {
            get {
                return ResourceManager.GetString("GORIMG_ERR_CONVERT_FORMAT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_EXPORT_CONVERT {
            get {
                return ResourceManager.GetString("GORIMG_ERR_EXPORT_CONVERT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_FORMAT_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("GORIMG_ERR_FORMAT_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_IMAGE_INFO {
            get {
                return ResourceManager.GetString("GORIMG_ERR_IMAGE_INFO", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_IMPORT_FAIL {
            get {
                return ResourceManager.GetString("GORIMG_ERR_IMPORT_FAIL", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_NO_CODEC {
            get {
                return ResourceManager.GetString("GORIMG_ERR_NO_CODEC", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_NO_CODECS {
            get {
                return ResourceManager.GetString("GORIMG_ERR_NO_CODECS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_NO_EXTERNAL_EDITOR {
            get {
                return ResourceManager.GetString("GORIMG_ERR_NO_EXTERNAL_EDITOR", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_REDO {
            get {
                return ResourceManager.GetString("GORIMG_ERR_REDO", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_SAVE_CONTENT {
            get {
                return ResourceManager.GetString("GORIMG_ERR_SAVE_CONTENT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_UNDO {
            get {
                return ResourceManager.GetString("GORIMG_ERR_UNDO", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_ERR_UPDATING_IMAGE {
            get {
                return ResourceManager.GetString("GORIMG_ERR_UPDATING_IMAGE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_FILEMASK_ALL_FILES {
            get {
                return ResourceManager.GetString("GORIMG_FILEMASK_ALL_FILES", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_FILTER_SELECT_CODEC {
            get {
                return ResourceManager.GetString("GORIMG_FILTER_SELECT_CODEC", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_IMPORT_DESC {
            get {
                return ResourceManager.GetString("GORIMG_IMPORT_DESC", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_RESIZE_CROP_DESC {
            get {
                return ResourceManager.GetString("GORIMG_RESIZE_CROP_DESC", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_SEARCH_KEYWORD_CODEC {
            get {
                return ResourceManager.GetString("GORIMG_SEARCH_KEYWORD_CODEC", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_3DVIEW {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_3DVIEW", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_ALIGN_TO {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_ALIGN_TO", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_ARRAY_INDEX {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_ARRAY_INDEX", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_ARRAY_INDEX_COUNT {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_ARRAY_INDEX_COUNT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_ARRAY_INDICES {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_ARRAY_INDICES", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_COLOR_VALUES {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_COLOR_VALUES", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_CROP_TO {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_CROP_TO", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_DEPTH_SLICE {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_DEPTH_SLICE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_DEPTH_SLICE_COUNT {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_DEPTH_SLICE_COUNT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_DEPTH_SLICES {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_DEPTH_SLICES", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_IMAGE_FORMAT {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_IMAGE_FORMAT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_IMAGE_SIZE_DETAILS {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_IMAGE_SIZE_DETAILS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_IMG_PICKER_INSTRUCTION {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_IMG_PICKER_INSTRUCTION", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_IMPORTING {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_IMPORTING", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_LOADING_IMAGES {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_LOADING_IMAGES", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_MIP_DETAILS {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_MIP_DETAILS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_MIP_MAPS {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_MIP_MAPS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_PLEASE_WAIT {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_PLEASE_WAIT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_RESIZE_CROP_IMAGE_SIZE {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_RESIZE_CROP_IMAGE_SIZE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_RESIZE_CROP_IMPORT_NAME {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_RESIZE_CROP_IMPORT_NAME", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_RESIZE_CROP_IMPORT_SIZE {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_RESIZE_CROP_IMPORT_SIZE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_RESIZE_TO {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_RESIZE_TO", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_SAVING {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_SAVING", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_SRC_IMG_PICKER_DESC_ARRAY {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_SRC_IMG_PICKER_DESC_ARRAY", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_SRC_IMG_PICKER_DESC_DEPTH {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_SRC_IMG_PICKER_DESC_DEPTH", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TEXT_ZOOM_BUTTON {
            get {
                return ResourceManager.GetString("GORIMG_TEXT_ZOOM_BUTTON", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TIP_DISABLED_FORMAT {
            get {
                return ResourceManager.GetString("GORIMG_TIP_DISABLED_FORMAT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TIP_IMAGE2D {
            get {
                return ResourceManager.GetString("GORIMG_TIP_IMAGE2D", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_TIP_IMAGE3D {
            get {
                return ResourceManager.GetString("GORIMG_TIP_IMAGE3D", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_UNDO_DESC_DIMENSIONS {
            get {
                return ResourceManager.GetString("GORIMG_UNDO_DESC_DIMENSIONS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_UNDO_DESC_EFFECTS {
            get {
                return ResourceManager.GetString("GORIMG_UNDO_DESC_EFFECTS", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_UNDO_DESC_FORMAT_CONVERT {
            get {
                return ResourceManager.GetString("GORIMG_UNDO_DESC_FORMAT_CONVERT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_UNDO_DESC_IMAGE_TYPE {
            get {
                return ResourceManager.GetString("GORIMG_UNDO_DESC_IMAGE_TYPE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_UNDO_DESC_IMPORT {
            get {
                return ResourceManager.GetString("GORIMG_UNDO_DESC_IMPORT", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_UNDO_DESC_IMPORT_SOURCE {
            get {
                return ResourceManager.GetString("GORIMG_UNDO_DESC_IMPORT_SOURCE", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_UNDO_DESC_MIP_GEN {
            get {
                return ResourceManager.GetString("GORIMG_UNDO_DESC_MIP_GEN", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string GORIMG_UNDO_DESC_SET_ALPHA {
            get {
                return ResourceManager.GetString("GORIMG_UNDO_DESC_SET_ALPHA", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap grayscale_16x16 {
            get {
                object obj = ResourceManager.GetObject("grayscale_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap grayscale_48x48 {
            get {
                object obj = ResourceManager.GetObject("grayscale_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap image_20x20 {
            get {
                object obj = ResourceManager.GetObject("image_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap image_dimensions_16x16 {
            get {
                object obj = ResourceManager.GetObject("image_dimensions_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap image_dimensions_48x48 {
            get {
                object obj = ResourceManager.GetObject("image_dimensions_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap image_effect_16x16 {
            get {
                object obj = ResourceManager.GetObject("image_effect_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap image_effect_48x48 {
            get {
                object obj = ResourceManager.GetObject("image_effect_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap image_size_16x16 {
            get {
                object obj = ResourceManager.GetObject("image_size_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap image_size_48x48 {
            get {
                object obj = ResourceManager.GetObject("image_size_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string ImageViewShaders {
            get {
                return ResourceManager.GetString("ImageViewShaders", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap import_image_16x16 {
            get {
                object obj = ResourceManager.GetObject("import_image_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap import_image_48x48 {
            get {
                object obj = ResourceManager.GetObject("import_image_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap invert_16x16 {
            get {
                object obj = ResourceManager.GetObject("invert_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap invert_48x48 {
            get {
                object obj = ResourceManager.GetObject("invert_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap left_16x16 {
            get {
                object obj = ResourceManager.GetObject("left_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap no_thumb_64x64 {
            get {
                object obj = ResourceManager.GetObject("no_thumb_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap onebit_16x16 {
            get {
                object obj = ResourceManager.GetObject("onebit_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap onebit_48x48 {
            get {
                object obj = ResourceManager.GetObject("onebit_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap opacity_48x48 {
            get {
                object obj = ResourceManager.GetObject("opacity_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap opactiy_16x16 {
            get {
                object obj = ResourceManager.GetObject("opactiy_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap pixel_format_16x16 {
            get {
                object obj = ResourceManager.GetObject("pixel_format_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap pixel_format_48x48 {
            get {
                object obj = ResourceManager.GetObject("pixel_format_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap posterize_16x16 {
            get {
                object obj = ResourceManager.GetObject("posterize_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap posterize_48x48 {
            get {
                object obj = ResourceManager.GetObject("posterize_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap redo_16x16 {
            get {
                object obj = ResourceManager.GetObject("redo_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap redo_48x48 {
            get {
                object obj = ResourceManager.GetObject("redo_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap remove_plugins_22x22 {
            get {
                object obj = ResourceManager.GetObject("remove_plugins_22x22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap right_16x16 {
            get {
                object obj = ResourceManager.GetObject("right_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap save_content_16x16 {
            get {
                object obj = ResourceManager.GetObject("save_content_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap save_content_48x48 {
            get {
                object obj = ResourceManager.GetObject("save_content_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap sharpen_16x16 {
            get {
                object obj = ResourceManager.GetObject("sharpen_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap sharpen_48x48 {
            get {
                object obj = ResourceManager.GetObject("sharpen_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap Transparency_Pattern {
            get {
                object obj = ResourceManager.GetObject("Transparency_Pattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap undo_16x16 {
            get {
                object obj = ResourceManager.GetObject("undo_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap undo_48x48 {
            get {
                object obj = ResourceManager.GetObject("undo_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static string VolumeRenderShaders {
            get {
                return ResourceManager.GetString("VolumeRenderShaders", resourceCulture);
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap zoom_16x16 {
            get {
                object obj = ResourceManager.GetObject("zoom_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        // Comment stripped.
        // Comment stripped.
        // Comment stripped.
        internal static System.Drawing.Bitmap zoom_48x48 {
            get {
                object obj = ResourceManager.GetObject("zoom_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
