//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgon.Editor.ImageEditor.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorgon.Editor.ImageEditor.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap add_plugin_22x22 {
        get {
            object obj = ResourceManager.GetObject("add_plugin_22x22", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap alpha_16x16 {
        get {
            object obj = ResourceManager.GetObject("alpha_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap alpha_48x48 {
        get {
            object obj = ResourceManager.GetObject("alpha_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap burn_16x16 {
        get {
            object obj = ResourceManager.GetObject("burn_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap burn_48x48 {
        get {
            object obj = ResourceManager.GetObject("burn_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap cancel_16x16 {
        get {
            object obj = ResourceManager.GetObject("cancel_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap cancel_48x48 {
        get {
            object obj = ResourceManager.GetObject("cancel_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap confirm_16x16 {
        get {
            object obj = ResourceManager.GetObject("confirm_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap confirm_48x48 {
        get {
            object obj = ResourceManager.GetObject("confirm_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap delete_16x16 {
        get {
            object obj = ResourceManager.GetObject("delete_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap dodge_16x16 {
        get {
            object obj = ResourceManager.GetObject("dodge_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap dodge_48x48 {
        get {
            object obj = ResourceManager.GetObject("dodge_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap edge_detect_16x16 {
        get {
            object obj = ResourceManager.GetObject("edge_detect_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap edge_detect_48x48 {
        get {
            object obj = ResourceManager.GetObject("edge_detect_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap edit_image_16x16 {
        get {
            object obj = ResourceManager.GetObject("edit_image_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap edit_image_48x48 {
        get {
            object obj = ResourceManager.GetObject("edit_image_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap emboss_16x16 {
        get {
            object obj = ResourceManager.GetObject("emboss_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap emboss_48x48 {
        get {
            object obj = ResourceManager.GetObject("emboss_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap export_image_16x16 {
        get {
            object obj = ResourceManager.GetObject("export_image_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap export_image_48x48 {
        get {
            object obj = ResourceManager.GetObject("export_image_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap gauss_blur_16x16 {
        get {
            object obj = ResourceManager.GetObject("gauss_blur_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap gauss_blur_48x48 {
        get {
            object obj = ResourceManager.GetObject("gauss_blur_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap generate_mip_maps_16x16 {
        get {
            object obj = ResourceManager.GetObject("generate_mip_maps_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap generate_mip_maps_48x48 {
        get {
            object obj = ResourceManager.GetObject("generate_mip_maps_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Export image as {0}....
    /// </summary>
    internal static string GORIMG_CAPTION_EXPORT_IMAGE {
        get {
            return ResourceManager.GetString("GORIMG_CAPTION_EXPORT_IMAGE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select images for import into {0}....
    /// </summary>
    internal static string GORIMG_CAPTION_IMG_PICKER {
        get {
            return ResourceManager.GetString("GORIMG_CAPTION_IMG_PICKER", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import image....
    /// </summary>
    internal static string GORIMG_CAPTION_IMPORT_IMAGE {
        get {
            return ResourceManager.GetString("GORIMG_CAPTION_IMPORT_IMAGE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select a codec plug in DLL.
    /// </summary>
    internal static string GORIMG_CAPTION_SELECT_CODEC_DLL {
        get {
            return ResourceManager.GetString("GORIMG_CAPTION_SELECT_CODEC_DLL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to This image has more than 1 depth slice. Converting this image to a 2D/Cube image will discard all depth slices after the 1st one.  
    ///
    ///Are you sure you wish to continue?.
    /// </summary>
    internal static string GORIMG_CONFIRM_3D_TO_2D {
        get {
            return ResourceManager.GetString("GORIMG_CONFIRM_3D_TO_2D", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to This image has an array. Converting to a volume (3D) image will discard these array indices after the 1st one.
    ///
    ///Are you sure you wish to continue?.
    /// </summary>
    internal static string GORIMG_CONFIRM_ARRAY_TO_VOLUME {
        get {
            return ResourceManager.GetString("GORIMG_CONFIRM_ARRAY_TO_VOLUME", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The image &apos;{0}&apos; has unsaved changes. 
    ///
    ///Would you like to save these changes now?.
    /// </summary>
    internal static string GORIMG_CONFIRM_CLOSE {
        get {
            return ResourceManager.GetString("GORIMG_CONFIRM_CLOSE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The codec &apos;{0}&apos; does not support the following:
    ///{1}
    ///
    ///Only the current mip level and array index, or depth slice will be exported, and the pixel format will be converted to an appropriate pixel format for the codec.
    ///
    ///Do you wish to continue?.
    /// </summary>
    internal static string GORIMG_CONFIRM_EXPORT_LIMITS {
        get {
            return ResourceManager.GetString("GORIMG_CONFIRM_EXPORT_LIMITS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There are mip map levels in this image. Generating new mip levels will overwrite these mip maps.
    ///
    ///Would you like to continue?.
    /// </summary>
    internal static string GORIMG_CONFIRM_GEN_MIPMAP {
        get {
            return ResourceManager.GetString("GORIMG_CONFIRM_GEN_MIPMAP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to This will overwrite the image data at array index {0}, mip level {1}.
    ///
    ///Continue?.
    /// </summary>
    internal static string GORIMG_CONFIRM_OVERWRITE_ARRAY_INDEX {
        get {
            return ResourceManager.GetString("GORIMG_CONFIRM_OVERWRITE_ARRAY_INDEX", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to This will overwrite the image data at depth slice {0}, mip level {1}.
    ///
    ///Continue?.
    /// </summary>
    internal static string GORIMG_CONFIRM_OVERWRITE_DEPTH_SLICE {
        get {
            return ResourceManager.GetString("GORIMG_CONFIRM_OVERWRITE_DEPTH_SLICE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to This will remove all codecs associated with the &apos;{0}&apos; plug in.
    ///
    ///Are you sure you want to do this?.
    /// </summary>
    internal static string GORIMG_CONFIRM_REMOVE_CODECS {
        get {
            return ResourceManager.GetString("GORIMG_CONFIRM_REMOVE_CODECS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Image.
    /// </summary>
    internal static string GORIMG_CONTENT_TYPE {
        get {
            return ResourceManager.GetString("GORIMG_CONTENT_TYPE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to At least one image dimension is smaller than the current image dimensions.  This will result in a loss of data in the image.
    ///
    ///Do you wish to continue?.
    /// </summary>
    internal static string GORIMG_CROP_LOSE_DATA {
        get {
            return ResourceManager.GetString("GORIMG_CROP_LOSE_DATA", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Gorgon Image Editor.
    /// </summary>
    internal static string GORIMG_DESC {
        get {
            return ResourceManager.GetString("GORIMG_DESC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Premultiplied alpha.
    /// </summary>
    internal static string GORIMG_DESC_UNDO_PREMULTIPLY {
        get {
            return ResourceManager.GetString("GORIMG_DESC_UNDO_PREMULTIPLY", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error applying effects to the image..
    /// </summary>
    internal static string GORIMG_ERR_APPLYING_EFFECTS {
        get {
            return ResourceManager.GetString("GORIMG_ERR_APPLYING_EFFECTS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error while compressing the image data.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_CANNOT_COMPRESS {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CANNOT_COMPRESS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The pixel format [{0}] cannot be converted to [{1}]..
    /// </summary>
    internal static string GORIMG_ERR_CANNOT_CONVERT {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CANNOT_CONVERT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error opening the image picker.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_CANNOT_OPEN_IMG_PICKER {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CANNOT_OPEN_IMG_PICKER", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The executable &apos;{0}&apos; could not be found. 
    ///
    ///Please locate an appropriate editor using the settings interface..
    /// </summary>
    internal static string GORIMG_ERR_CANT_FIND_EDITOR {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CANT_FIND_EDITOR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error while converting the image type..
    /// </summary>
    internal static string GORIMG_ERR_CHANGE_TYPE {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CHANGE_TYPE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The codec &apos;{0}&apos; was already loaded..
    /// </summary>
    internal static string GORIMG_ERR_CODEC_ALREADY_LOADED {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CODEC_ALREADY_LOADED", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error changing the codec.
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_CODEC_ASSIGN {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CODEC_ASSIGN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There were errors while trying to load the codec plug in.
    ///
    ///Please check the Details pane for more information..
    /// </summary>
    internal static string GORIMG_ERR_CODEC_LOAD_ERRORS_PRESENT {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CODEC_LOAD_ERRORS_PRESENT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error loading the &apos;{0}&apos; codec..
    /// </summary>
    internal static string GORIMG_ERR_CODEC_LOAD_FAIL {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CODEC_LOAD_FAIL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The codec plug in &apos;{0}&apos; was already loaded..
    /// </summary>
    internal static string GORIMG_ERR_CODEC_PLUGIN_ALREADY_LOADED {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CODEC_PLUGIN_ALREADY_LOADED", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The file is compressed using [{0}], and currently there is no support for decompressing it..
    /// </summary>
    internal static string GORIMG_ERR_COMPRESSED_FILE {
        get {
            return ResourceManager.GetString("GORIMG_ERR_COMPRESSED_FILE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to This image is using a compressed format [{0}]. Compressed formats require that the image width and height be a multiple of 4.  
    ///
    ///The request image size ({1}x{2}) is not a multiple of 4..
    /// </summary>
    internal static string GORIMG_ERR_COMPRESSED_RESIZE_MULTIPLE_4 {
        get {
            return ResourceManager.GetString("GORIMG_ERR_COMPRESSED_RESIZE_MULTIPLE_4", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error converting the format to [{0}].
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_CONVERT_FORMAT {
        get {
            return ResourceManager.GetString("GORIMG_ERR_CONVERT_FORMAT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cannot convert [{0}] to a format supported by the codec..
    /// </summary>
    internal static string GORIMG_ERR_EXPORT_CONVERT {
        get {
            return ResourceManager.GetString("GORIMG_ERR_EXPORT_CONVERT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There is no support for the [{0}] format..
    /// </summary>
    internal static string GORIMG_ERR_FORMAT_NOT_SUPPORTED {
        get {
            return ResourceManager.GetString("GORIMG_ERR_FORMAT_NOT_SUPPORTED", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error while trying to retrieve the current image information.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_IMAGE_INFO {
        get {
            return ResourceManager.GetString("GORIMG_ERR_IMAGE_INFO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error importing the file &apos;{0}&apos;..
    /// </summary>
    internal static string GORIMG_ERR_IMPORT_FAIL {
        get {
            return ResourceManager.GetString("GORIMG_ERR_IMPORT_FAIL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There is no codec loaded that can read the file &apos;{0}&apos;..
    /// </summary>
    internal static string GORIMG_ERR_NO_CODEC {
        get {
            return ResourceManager.GetString("GORIMG_ERR_NO_CODEC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The DLL &apos;{0}&apos; does not contain any image codecs.
    ///
    ///Choose another DLL and try again..
    /// </summary>
    internal static string GORIMG_ERR_NO_CODECS {
        get {
            return ResourceManager.GetString("GORIMG_ERR_NO_CODECS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Could not find an external editor that can open &apos;{0}&apos;..
    /// </summary>
    internal static string GORIMG_ERR_NO_EXTERNAL_EDITOR {
        get {
            return ResourceManager.GetString("GORIMG_ERR_NO_EXTERNAL_EDITOR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error performing the redo action.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_REDO {
        get {
            return ResourceManager.GetString("GORIMG_ERR_REDO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error saving the content.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_SAVE_CONTENT {
        get {
            return ResourceManager.GetString("GORIMG_ERR_SAVE_CONTENT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error while setting the application path.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_SETTING_EXE_PATH {
        get {
            return ResourceManager.GetString("GORIMG_ERR_SETTING_EXE_PATH", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error performing the undo action.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_UNDO {
        get {
            return ResourceManager.GetString("GORIMG_ERR_UNDO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to There was an error updating the image.
    ///
    ///Please try again..
    /// </summary>
    internal static string GORIMG_ERR_UPDATING_IMAGE {
        get {
            return ResourceManager.GetString("GORIMG_ERR_UPDATING_IMAGE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to All files (*.*)|*.*.
    /// </summary>
    internal static string GORIMG_FILEMASK_ALL_FILES {
        get {
            return ResourceManager.GetString("GORIMG_FILEMASK_ALL_FILES", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Codec plug in file (*.dll)|*.dll.
    /// </summary>
    internal static string GORIMG_FILTER_SELECT_CODEC {
        get {
            return ResourceManager.GetString("GORIMG_FILTER_SELECT_CODEC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Gorgon Image Importer.
    /// </summary>
    internal static string GORIMG_IMPORT_DESC {
        get {
            return ResourceManager.GetString("GORIMG_IMPORT_DESC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The dimensions of the image &apos;{0}&apos; do not match the dimensions of the target image. 
    ///
    ///Chose one of the options below to fit the imported image into the dimensions of the target image..
    /// </summary>
    internal static string GORIMG_RESIZE_CROP_DESC {
        get {
            return ResourceManager.GetString("GORIMG_RESIZE_CROP_DESC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to codec.
    /// </summary>
    internal static string GORIMG_SEARCH_KEYWORD_CODEC {
        get {
            return ResourceManager.GetString("GORIMG_SEARCH_KEYWORD_CODEC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Gorgon Image Editor.
    /// </summary>
    internal static string GORIMG_SETTINGS_DESC {
        get {
            return ResourceManager.GetString("GORIMG_SETTINGS_DESC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to 3D View.
    /// </summary>
    internal static string GORIMG_TEXT_3DVIEW {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_3DVIEW", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Align.
    /// </summary>
    internal static string GORIMG_TEXT_ALIGN_TO {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_ALIGN_TO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Array Index:.
    /// </summary>
    internal static string GORIMG_TEXT_ARRAY_INDEX {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_ARRAY_INDEX", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Array index count:.
    /// </summary>
    internal static string GORIMG_TEXT_ARRAY_INDEX_COUNT {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_ARRAY_INDEX_COUNT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Array Indices.
    /// </summary>
    internal static string GORIMG_TEXT_ARRAY_INDICES {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_ARRAY_INDICES", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Red: {0} Green: {1} Blue: {2}
    ///Alpha: {3}.
    /// </summary>
    internal static string GORIMG_TEXT_COLOR_VALUES {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_COLOR_VALUES", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Crop to {0}x{1}.
    /// </summary>
    internal static string GORIMG_TEXT_CROP_TO {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_CROP_TO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Depth Slice:.
    /// </summary>
    internal static string GORIMG_TEXT_DEPTH_SLICE {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_DEPTH_SLICE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Depth slice count:.
    /// </summary>
    internal static string GORIMG_TEXT_DEPTH_SLICE_COUNT {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_DEPTH_SLICE_COUNT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Depth Slices.
    /// </summary>
    internal static string GORIMG_TEXT_DEPTH_SLICES {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_DEPTH_SLICES", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Pixel Format.
    /// </summary>
    internal static string GORIMG_TEXT_IMAGE_FORMAT {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_IMAGE_FORMAT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Image width and height: {0}x{1}.
    /// </summary>
    internal static string GORIMG_TEXT_IMAGE_SIZE_DETAILS {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_IMAGE_SIZE_DETAILS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Drag an image into the panel below to import into {0}..
    /// </summary>
    internal static string GORIMG_TEXT_IMG_PICKER_INSTRUCTION {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_IMG_PICKER_INSTRUCTION", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Importing....
    /// </summary>
    internal static string GORIMG_TEXT_IMPORTING {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_IMPORTING", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Loading Image(s)....
    /// </summary>
    internal static string GORIMG_TEXT_LOADING_IMAGES {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_LOADING_IMAGES", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0}/{1} ({2}x{3}).
    /// </summary>
    internal static string GORIMG_TEXT_MIP_DETAILS {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_MIP_DETAILS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mip Maps.
    /// </summary>
    internal static string GORIMG_TEXT_MIP_MAPS {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_MIP_MAPS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Please wait....
    /// </summary>
    internal static string GORIMG_TEXT_PLEASE_WAIT {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_PLEASE_WAIT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Target image dimensions: {0}x{1}.
    /// </summary>
    internal static string GORIMG_TEXT_RESIZE_CROP_IMAGE_SIZE {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_RESIZE_CROP_IMAGE_SIZE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import image name: {0}.
    /// </summary>
    internal static string GORIMG_TEXT_RESIZE_CROP_IMPORT_NAME {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_RESIZE_CROP_IMPORT_NAME", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import image dimensions: {0}x{1}.
    /// </summary>
    internal static string GORIMG_TEXT_RESIZE_CROP_IMPORT_SIZE {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_RESIZE_CROP_IMPORT_SIZE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Resize to {0}x{1}.
    /// </summary>
    internal static string GORIMG_TEXT_RESIZE_TO {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_RESIZE_TO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Saving &apos;{0}&apos;....
    /// </summary>
    internal static string GORIMG_TEXT_SAVING {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_SAVING", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The source image &apos;{0}&apos; has multiple array indices and/or multiple mip map levels.
    ///
    ///Please select an array index to import from the source image..
    /// </summary>
    internal static string GORIMG_TEXT_SRC_IMG_PICKER_DESC_ARRAY {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_SRC_IMG_PICKER_DESC_ARRAY", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to The source image &apos;{0}&apos; has multiple depth slices and/or multiple mip map levels.
    ///
    ///Please select an depth slice to import from the source image..
    /// </summary>
    internal static string GORIMG_TEXT_SRC_IMG_PICKER_DESC_DEPTH {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_SRC_IMG_PICKER_DESC_DEPTH", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Zoom: {0}.
    /// </summary>
    internal static string GORIMG_TEXT_ZOOM_BUTTON {
        get {
            return ResourceManager.GetString("GORIMG_TEXT_ZOOM_BUTTON", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to [{0}] is disabled because the image width or height is not a multiple of 4..
    /// </summary>
    internal static string GORIMG_TIP_DISABLED_FORMAT {
        get {
            return ResourceManager.GetString("GORIMG_TIP_DISABLED_FORMAT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Image Type: {0}
    ///Size: {1}x{2}
    ///Format: {3}
    ///Array Count: {4}
    ///Mip Count: {5}.
    /// </summary>
    internal static string GORIMG_TIP_IMAGE2D {
        get {
            return ResourceManager.GetString("GORIMG_TIP_IMAGE2D", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Image Type: {0}
    ///Size: {1}x{2}x{3}
    ///Format: {4}
    ///Mip Count: {5}.
    /// </summary>
    internal static string GORIMG_TIP_IMAGE3D {
        get {
            return ResourceManager.GetString("GORIMG_TIP_IMAGE3D", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Image dimensions.
    /// </summary>
    internal static string GORIMG_UNDO_DESC_DIMENSIONS {
        get {
            return ResourceManager.GetString("GORIMG_UNDO_DESC_DIMENSIONS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Apply effects to image.
    /// </summary>
    internal static string GORIMG_UNDO_DESC_EFFECTS {
        get {
            return ResourceManager.GetString("GORIMG_UNDO_DESC_EFFECTS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Conversion to pixel format [{0}].
    /// </summary>
    internal static string GORIMG_UNDO_DESC_FORMAT_CONVERT {
        get {
            return ResourceManager.GetString("GORIMG_UNDO_DESC_FORMAT_CONVERT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Image Type &apos;{0}&apos;.
    /// </summary>
    internal static string GORIMG_UNDO_DESC_IMAGE_TYPE {
        get {
            return ResourceManager.GetString("GORIMG_UNDO_DESC_IMAGE_TYPE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import file &apos;{0}&apos;.
    /// </summary>
    internal static string GORIMG_UNDO_DESC_IMPORT {
        get {
            return ResourceManager.GetString("GORIMG_UNDO_DESC_IMPORT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import files..
    /// </summary>
    internal static string GORIMG_UNDO_DESC_IMPORT_SOURCE {
        get {
            return ResourceManager.GetString("GORIMG_UNDO_DESC_IMPORT_SOURCE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mipmap generation.
    /// </summary>
    internal static string GORIMG_UNDO_DESC_MIP_GEN {
        get {
            return ResourceManager.GetString("GORIMG_UNDO_DESC_MIP_GEN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Set alpha value.
    /// </summary>
    internal static string GORIMG_UNDO_DESC_SET_ALPHA {
        get {
            return ResourceManager.GetString("GORIMG_UNDO_DESC_SET_ALPHA", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap grayscale_16x16 {
        get {
            object obj = ResourceManager.GetObject("grayscale_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap grayscale_48x48 {
        get {
            object obj = ResourceManager.GetObject("grayscale_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap image_20x20 {
        get {
            object obj = ResourceManager.GetObject("image_20x20", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap image_dimensions_16x16 {
        get {
            object obj = ResourceManager.GetObject("image_dimensions_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap image_dimensions_48x48 {
        get {
            object obj = ResourceManager.GetObject("image_dimensions_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap image_effect_16x16 {
        get {
            object obj = ResourceManager.GetObject("image_effect_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap image_effect_48x48 {
        get {
            object obj = ResourceManager.GetObject("image_effect_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap image_size_16x16 {
        get {
            object obj = ResourceManager.GetObject("image_size_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap image_size_48x48 {
        get {
            object obj = ResourceManager.GetObject("image_size_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to // Shaders for image viewing.
    ///#GorgonInclude &quot;Gorgon2DShaders&quot;
    ///
    ///// Our default texture and sampler.
    ///Texture2DArray _gorgonTexture2DArray : register(t0);
    ///TextureCube _gorgonTextureVolume : register(t0);
    ///Texture3D _gorgonTexture3D : register(t1);			// Store this in slot 1 so that we can render a slice using our 2D renderer (which only accepts 2D views)..
    ///SamplerState _gorgon3DSampler : register(s1);
    ///
    ///// The texture parameters
    ///cbuffer GorgonTextureParams : register(b1)
    ///{
    ///	// Depth slice to view.
    ///	 [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string ImageViewShaders {
        get {
            return ResourceManager.GetString("ImageViewShaders", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap import_image_16x16 {
        get {
            object obj = ResourceManager.GetObject("import_image_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap import_image_48x48 {
        get {
            object obj = ResourceManager.GetObject("import_image_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap invert_16x16 {
        get {
            object obj = ResourceManager.GetObject("invert_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap invert_48x48 {
        get {
            object obj = ResourceManager.GetObject("invert_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap left_16x16 {
        get {
            object obj = ResourceManager.GetObject("left_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap no_thumb_64x64 {
        get {
            object obj = ResourceManager.GetObject("no_thumb_64x64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap onebit_16x16 {
        get {
            object obj = ResourceManager.GetObject("onebit_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap onebit_48x48 {
        get {
            object obj = ResourceManager.GetObject("onebit_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap opacity_48x48 {
        get {
            object obj = ResourceManager.GetObject("opacity_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap opactiy_16x16 {
        get {
            object obj = ResourceManager.GetObject("opactiy_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap open_folder_16x16 {
        get {
            object obj = ResourceManager.GetObject("open_folder_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap pixel_format_16x16 {
        get {
            object obj = ResourceManager.GetObject("pixel_format_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap pixel_format_48x48 {
        get {
            object obj = ResourceManager.GetObject("pixel_format_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap posterize_16x16 {
        get {
            object obj = ResourceManager.GetObject("posterize_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap posterize_48x48 {
        get {
            object obj = ResourceManager.GetObject("posterize_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap redo_16x16 {
        get {
            object obj = ResourceManager.GetObject("redo_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap redo_48x48 {
        get {
            object obj = ResourceManager.GetObject("redo_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap remove_plugins_22x22 {
        get {
            object obj = ResourceManager.GetObject("remove_plugins_22x22", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap right_16x16 {
        get {
            object obj = ResourceManager.GetObject("right_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap save_content_16x16 {
        get {
            object obj = ResourceManager.GetObject("save_content_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap save_content_48x48 {
        get {
            object obj = ResourceManager.GetObject("save_content_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap sharpen_16x16 {
        get {
            object obj = ResourceManager.GetObject("sharpen_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap sharpen_48x48 {
        get {
            object obj = ResourceManager.GetObject("sharpen_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Transparency_Pattern {
        get {
            object obj = ResourceManager.GetObject("Transparency_Pattern", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap undo_16x16 {
        get {
            object obj = ResourceManager.GetObject("undo_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap undo_48x48 {
        get {
            object obj = ResourceManager.GetObject("undo_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to // Our default texture and sampler.
    ///Texture3D _volumeTexture : register(t0);
    ///SamplerState _volumeSampler : register(s0);
    ///Texture2D _cubeFront : register(t1);
    ///SamplerState _cubeFrontSampler : register(s1);
    ///Texture2D _cubeBack : register(t2);
    ///SamplerState _cubeBackSampler : register(s2);
    ///
    ///// A vertex for the volume cube.
    ///struct VolumeVertex
    ///{	
    ///	float4 position : SV_POSITION;
    ///	float3 uvw : TEXCOORD;
    ///};
    ///
    ///// A vertex for a cube.
    ///struct VolumeVertexOut
    ///{	
    ///	// The position of the vertex.
    ///	float4 [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string VolumeRenderShaders {
        get {
            return ResourceManager.GetString("VolumeRenderShaders", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap zoom_16x16 {
        get {
            object obj = ResourceManager.GetObject("zoom_16x16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap zoom_48x48 {
        get {
            object obj = ResourceManager.GetObject("zoom_48x48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
