//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorgonLibrary.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GorgonLibrary.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_16x16 {
            get {
                object obj = ResourceManager.GetObject("add_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_16x16png {
            get {
                object obj = ResourceManager.GetObject("back_16x16png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_16x16 {
            get {
                object obj = ResourceManager.GetObject("cancel_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Check_Disabled {
            get {
                object obj = ResourceManager.GetObject("Check_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Check_Enabled {
            get {
                object obj = ResourceManager.GetObject("Check_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap choose_view_16x16 {
            get {
                object obj = ResourceManager.GetObject("choose_view_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_item_16x16 {
            get {
                object obj = ResourceManager.GetObject("delete_item_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_16x16 {
            get {
                object obj = ResourceManager.GetObject("edit_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expando {
            get {
                object obj = ResourceManager.GetObject("Expando", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find_16x16 {
            get {
                object obj = ResourceManager.GetObject("find_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_open_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_16x16 {
            get {
                object obj = ResourceManager.GetObject("forward_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;content.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_ADD_CONTENT {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_ADD_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_CANCEL {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_COPY {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;folder.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_CREATE_FOLDER {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_CREATE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_CUT {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_DELETE {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete all files and folders.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_DELETE_ALL_FILES {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_DELETE_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete folder.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_DELETE_FOLDER {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_DELETE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Disable.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_DISABLE_PLUGIN {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_DISABLE_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_EDIT {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enable.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_ENABLE_PLUGIN {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_ENABLE_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_EXIT {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_EXPORT {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_IMPORT {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_NEW {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_OK {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_OPEN {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_PASTE {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Preferences.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_PREFERENCES {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recent files.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_RECENT_FILES {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_RECENT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_RENAME {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename folder.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_RENAME_FOLDER {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_RENAME_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset value.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_RESET_VALUE {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_RESET_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_SAVE {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;as.
        /// </summary>
        internal static string GOREDIT_ACC_TEXT_SAVE_AS {
            get {
                return ResourceManager.GetString("GOREDIT_ACC_TEXT_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any changes to the plug-in list will not take effect until the application is restarted..
        /// </summary>
        internal static string GOREDIT_DLG_APP_NEEDS_RESTART {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_APP_NEEDS_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; has dependencies that could not be loaded.  The file was loaded normally, but may not function correctly.  Please see the details pane to see which dependency files did not load correctly..
        /// </summary>
        internal static string GOREDIT_DLG_CANNOT_FIND_DEPENDENCY {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_CANNOT_FIND_DEPENDENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}
        ///Error: {1}
        ///.
        /// </summary>
        internal static string GOREDIT_DLG_CANNOT_LOAD_DEPENDENCY {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_CANNOT_LOAD_DEPENDENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &apos;{1}&apos; has unsaved changes. Would you like to save the {0} now?.
        /// </summary>
        internal static string GOREDIT_DLG_CONTENT_CHANGED_SAVE {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_CONTENT_CHANGED_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the thumbnail for the file &apos;{0}&apos;..
        /// </summary>
        internal static string GOREDIT_DLG_COULD_NOT_LOAD_THUMBNAIL {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_COULD_NOT_LOAD_THUMBNAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete &apos;{0}&apos; and any files and/or directories it contains.  Are you sure you wish to do this?.
        /// </summary>
        internal static string GOREDIT_DLG_DELETE_DIRECTORY {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_DELETE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete &apos;{0}&apos;.  Are you sure you wish to do this?.
        /// </summary>
        internal static string GOREDIT_DLG_DELETE_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_DELETE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will disable the plug in &apos;{0}&apos;.  Are you sure wish to do this?.
        /// </summary>
        internal static string GOREDIT_DLG_DISABLE_PLUGIN {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_DISABLE_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export operation was cancelled.
        ///{0}/{1} files copied.
        ///{2}/{1} files skipped..
        /// </summary>
        internal static string GOREDIT_DLG_EXPORT_CANCELLED {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_EXPORT_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is dependent upon other files in the file system.  Would you like to export these dependencies with the file?.
        /// </summary>
        internal static string GOREDIT_DLG_EXPORT_DEPENDENCIES {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_EXPORT_DEPENDENCIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination directory must not be a sub-directory of this directory..
        /// </summary>
        internal static string GOREDIT_DLG_FILE_CANNOT_MOVE_TO_CHILD {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_FILE_CANNOT_MOVE_TO_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editor file &apos;{0}&apos; has unsaved changes.  Would you like to save these changes?.
        /// </summary>
        internal static string GOREDIT_DLG_FILE_HAS_CHANGES {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_FILE_HAS_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source file must not be the same as the destination file..
        /// </summary>
        internal static string GOREDIT_DLG_FILE_SOURCE_SAME_AS_DEST {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_FILE_SOURCE_SAME_AS_DEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must close and re-open the current content to use the new image editor..
        /// </summary>
        internal static string GOREDIT_DLG_IMAGE_EDITOR_CHANGED {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_IMAGE_EDITOR_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import operation was cancelled.
        ///{0}/{1} files and directories copied.
        ///{2}/{1} files and directories skipped..
        /// </summary>
        internal static string GOREDIT_DLG_IMPORT_CANCELLED {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_IMPORT_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files and {1} directories will be imported.  Are you sure you wish to do this?.
        /// </summary>
        internal static string GOREDIT_DLG_IMPORT_CONFIRM {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_IMPORT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is opened for editing.  You must close this file and reimport it if you wish to overwrite it..
        /// </summary>
        internal static string GOREDIT_DLG_IMPORT_FILE_OPEN_FOR_EDIT {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_IMPORT_FILE_OPEN_FOR_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no files/directories found that could be imported..
        /// </summary>
        internal static string GOREDIT_DLG_IMPORT_NO_DATA {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_IMPORT_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open &apos;{0}&apos;.  There are no content plug-ins loaded that can open &apos;{1}&apos; files..
        /// </summary>
        internal static string GOREDIT_DLG_NO_CONTENT_PLUG_IN_FOR_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_NO_CONTENT_PLUG_IN_FOR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no file in the path &apos;{0}&apos;..
        /// </summary>
        internal static string GOREDIT_DLG_NO_FILE_IN_PATH {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_NO_FILE_IN_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no directory named &apos;{0}&apos;..
        /// </summary>
        internal static string GOREDIT_DLG_NO_SUCH_DIRECTORY {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_NO_SUCH_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no file named &apos;{0}{1}&apos;..
        /// </summary>
        internal static string GOREDIT_DLG_NO_SUCH_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_NO_SUCH_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening &apos;{0}&apos;..
        /// </summary>
        internal static string GOREDIT_DLG_OPEN_ERROR {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_OPEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; already exists.  Would you like to merge the two directories together?.
        /// </summary>
        internal static string GOREDIT_DLG_OVERWRITE_DIRECTORY {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_OVERWRITE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &apos;{1}&apos; already exists.  Do you wish to overwrite it?.
        /// </summary>
        internal static string GOREDIT_DLG_OVERWRITE_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_OVERWRITE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination must be a directory..
        /// </summary>
        internal static string GOREDIT_DLG_PASTE_MUST_BE_DIRECTORY {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_PASTE_MUST_BE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plug-in &apos;{0}&apos; failed to load.
        /// </summary>
        internal static string GOREDIT_DLG_PLUG_IN_FAIL_REASON {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_PLUG_IN_FAIL_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plug-in location has changed.  This will require that the application be restarted before this setting takes effect..
        /// </summary>
        internal static string GOREDIT_DLG_PLUGIN_LOC_CHANGE {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_PLUGIN_LOC_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scratch location has changed.  This will require that the application be restarted before this setting takes effect..
        /// </summary>
        internal static string GOREDIT_DLG_SCRATCH_LOC_CHANGE {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_SCRATCH_LOC_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new temporary scratch path..
        /// </summary>
        internal static string GOREDIT_DLG_SCRATCH_PATH {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_SCRATCH_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more settings are invalid.  Please correct the invalid settings and try again..
        /// </summary>
        internal static string GOREDIT_DLG_SETTINGS_INVALID {
            get {
                return ResourceManager.GetString("GOREDIT_DLG_SETTINGS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dependency file, &apos;{0}&apos; is missing and must exist to load the content..
        /// </summary>
        internal static string GOREDIT_ERR_CANNOT_FIND_DEPENDENCY_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_CANNOT_FIND_DEPENDENCY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading dependency &apos;{0}&apos;.  The content requires this dependency and cannot be loaded without it.\nError: {1}.
        /// </summary>
        internal static string GOREDIT_ERR_CANNOT_LOAD_DEPENDENCY {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_CANNOT_LOAD_DEPENDENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use a system location or the root of the system drive for scratch data..
        /// </summary>
        internal static string GOREDIT_ERR_CANNOT_USESYS_SCRATCH {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_CANNOT_USESYS_SCRATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the content file &apos;{0}&apos;..
        /// </summary>
        internal static string GOREDIT_ERR_CONTENT_CANNOT_CREATE_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_CONTENT_CANNOT_CREATE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the dependency. It has been corrupted..
        /// </summary>
        internal static string GOREDIT_ERR_DEPENDENCY_CORRUPT {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_DEPENDENCY_CORRUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} dependency &apos;{1}&apos; already exists in this collection..
        /// </summary>
        internal static string GOREDIT_ERR_DEPENDENCY_EXISTS {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_DEPENDENCY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the dependency property.  It has been corrupted..
        /// </summary>
        internal static string GOREDIT_ERR_DEPENDENCY_PROP_CORRUPT {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_DEPENDENCY_PROP_CORRUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency property &apos;{0}&apos; does not exist in this collection..
        /// </summary>
        internal static string GOREDIT_ERR_DEPENDENCY_PROP_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_DEPENDENCY_PROP_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a dependency property with the name of &apos;{0}&apos; in this collection..
        /// </summary>
        internal static string GOREDIT_ERR_DEPENDENCY_PROP_EXISTS {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_DEPENDENCY_PROP_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency property needs a name..
        /// </summary>
        internal static string GOREDIT_ERR_DEPENDENCY_PROP_NO_NAME {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_DEPENDENCY_PROP_NO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &apos;{1}&apos; already exists..
        /// </summary>
        internal static string GOREDIT_ERR_FILE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_FILE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy &apos;{0}&apos; because the destination is a sub folder of this folder..
        /// </summary>
        internal static string GOREDIT_ERR_FILE_DIRECTORY_IS_CHILD {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_FILE_DIRECTORY_IS_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the file &apos;{0}&apos;..
        /// </summary>
        internal static string GOREDIT_ERR_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name contains invalid characters.
        ///The following characters are not allowed:
        ///{0}.
        /// </summary>
        internal static string GOREDIT_ERR_FILE_PATH_INVALID_CHARS {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_FILE_PATH_INVALID_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the raw input interface DLL..
        /// </summary>
        internal static string GOREDIT_ERR_INPUT_COULD_NOT_LOAD {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_INPUT_COULD_NOT_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meta data for the file is corrupted..
        /// </summary>
        internal static string GOREDIT_ERR_METADATA_CORRUPT {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_METADATA_CORRUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application settings were not loaded..
        /// </summary>
        internal static string GOREDIT_ERR_NO_APP_SETTINGS {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_NO_APP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no drives on the system with enough free space.  The Gorgon Editor requires a minimum of 150 MB of free space for temporary files..
        /// </summary>
        internal static string GOREDIT_ERR_NO_DRIVE_AVAILABLE {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_NO_DRIVE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editor does not know how to read the file &apos;{0}&apos;..
        /// </summary>
        internal static string GOREDIT_ERR_NO_READ_PROVIDERS {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_NO_READ_PROVIDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write the file &apos;{0}&apos;.  There is no plug-in available to write the file with..
        /// </summary>
        internal static string GOREDIT_ERR_NO_WRITER_PLUGIN {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_NO_WRITER_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must not be empty..
        /// </summary>
        internal static string GOREDIT_ERR_PARAMETER_MUST_NOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_PARAMETER_MUST_NOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; does not exist for this content..
        /// </summary>
        internal static string GOREDIT_ERR_PROPERTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_PROPERTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read beyond the end of the stream..
        /// </summary>
        internal static string GOREDIT_ERR_STREAM_EOS {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_STREAM_EOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is read only..
        /// </summary>
        internal static string GOREDIT_ERR_STREAM_READ_ONLY {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_STREAM_READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is write only..
        /// </summary>
        internal static string GOREDIT_ERR_STREAM_WRITE_ONLY {
            get {
                return ResourceManager.GetString("GOREDIT_ERR_STREAM_WRITE_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All content types.
        /// </summary>
        internal static string GOREDIT_TEXT_ALL_CONTENT {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_ALL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*).
        /// </summary>
        internal static string GOREDIT_TEXT_ALL_FILES {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string GOREDIT_TEXT_ALPHA {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate the Gorgon logo on the start up screen.
        /// </summary>
        internal static string GOREDIT_TEXT_ANIMATE_LOGO {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_ANIMATE_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation speed.
        /// </summary>
        internal static string GOREDIT_TEXT_ANIMATE_SPEED {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_ANIMATE_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available plug-ins.
        /// </summary>
        internal static string GOREDIT_TEXT_AVAILABLE_PLUGINS {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_AVAILABLE_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string GOREDIT_TEXT_BACK {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Broken link).
        /// </summary>
        internal static string GOREDIT_TEXT_BROKEN_LINK {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_BROKEN_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change file views..
        /// </summary>
        internal static string GOREDIT_TEXT_CHANGEVIEW {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_CHANGEVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string GOREDIT_TEXT_CONTENT {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content files.
        /// </summary>
        internal static string GOREDIT_TEXT_CONTENT_FILES {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_CONTENT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        internal static string GOREDIT_TEXT_COPYING {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_COPYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating &apos;{0}&apos;.
        /// </summary>
        internal static string GOREDIT_TEXT_CREATING {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_CREATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating scratch area....
        /// </summary>
        internal static string GOREDIT_TEXT_CREATING_SCRATCH {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_CREATING_SCRATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string GOREDIT_TEXT_DATE {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected content.
        /// </summary>
        internal static string GOREDIT_TEXT_DELETE_CONTENT {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_DELETE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency property &apos;{0}&apos;: &apos;{1}&apos;.
        /// </summary>
        internal static string GOREDIT_TEXT_DEPENDENCY_PROP {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_DEPENDENCY_PROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string GOREDIT_TEXT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail view.
        /// </summary>
        internal static string GOREDIT_TEXT_DETAIL_VIEW {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_DETAIL_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directory.
        /// </summary>
        internal static string GOREDIT_TEXT_DIRECTORY {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string GOREDIT_TEXT_DISABLED {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled by user..
        /// </summary>
        internal static string GOREDIT_TEXT_DISABLED_BY_USER {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_DISABLED_BY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected content.
        /// </summary>
        internal static string GOREDIT_TEXT_EDIT_CONTENT {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_EDIT_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string GOREDIT_TEXT_EDITOR_OPTIONS {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_EDITOR_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor paths.
        /// </summary>
        internal static string GOREDIT_TEXT_EDITOR_PATHS {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_EDITOR_PATHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor preferences.
        /// </summary>
        internal static string GOREDIT_TEXT_EDITOR_PREFERENCES {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_EDITOR_PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string GOREDIT_TEXT_ERROR {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        internal static string GOREDIT_TEXT_EXPORTING {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_EXPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed plug-ins.
        /// </summary>
        internal static string GOREDIT_TEXT_FAILED_PLUGINS {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_FAILED_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string GOREDIT_TEXT_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reader.
        /// </summary>
        internal static string GOREDIT_TEXT_FILE_READER {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_FILE_READER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File writer.
        /// </summary>
        internal static string GOREDIT_TEXT_FILE_WRITER {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_FILE_WRITER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string GOREDIT_TEXT_FILES {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting file information....
        /// </summary>
        internal static string GOREDIT_TEXT_GET_FILE_INFO {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_GET_FILE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward.
        /// </summary>
        internal static string GOREDIT_TEXT_GO_FORWARD {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_GO_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go up to the parent of this directory..
        /// </summary>
        internal static string GOREDIT_TEXT_GO_UP_TO_PARENT {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_GO_UP_TO_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorgon editor.
        /// </summary>
        internal static string GOREDIT_TEXT_GORGON_EDITOR {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_GORGON_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorgon editor Files.
        /// </summary>
        internal static string GOREDIT_TEXT_GORGON_FILES {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_GORGON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string GOREDIT_TEXT_HELP {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default image editor.
        /// </summary>
        internal static string GOREDIT_TEXT_IMAGE_EDITOR {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_IMAGE_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing.
        /// </summary>
        internal static string GOREDIT_TEXT_IMPORTING {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_IMPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing graphics....
        /// </summary>
        internal static string GOREDIT_TEXT_INITIALIZE_GRAPHICS {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_INITIALIZE_GRAPHICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string GOREDIT_TEXT_INITIALIZING {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading default content pane..
        /// </summary>
        internal static string GOREDIT_TEXT_LOAD_DEFAULT {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_LOAD_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load last opened file on editor start up.
        /// </summary>
        internal static string GOREDIT_TEXT_LOAD_LAST_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_LOAD_LAST_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading previous editor file....
        /// </summary>
        internal static string GOREDIT_TEXT_LOAD_PREV_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_LOAD_PREV_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading raw input interface....
        /// </summary>
        internal static string GOREDIT_TEXT_LOAD_RAW_INPUT {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_LOAD_RAW_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading plug-ins....
        /// </summary>
        internal static string GOREDIT_TEXT_LOADING_PLUGINS {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_LOADING_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving files.
        /// </summary>
        internal static string GOREDIT_TEXT_MOVING {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_MOVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string GOREDIT_TEXT_NAME {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New alpha.
        /// </summary>
        internal static string GOREDIT_TEXT_NEW_ALPHA {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_NEW_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New content item.
        /// </summary>
        internal static string GOREDIT_TEXT_NEW_CONTENT {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_NEW_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        internal static string GOREDIT_TEXT_NEW_NAME {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_NEW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old alpha.
        /// </summary>
        internal static string GOREDIT_TEXT_OLD_ALPHA {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_OLD_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string GOREDIT_TEXT_PATH {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick an alpha value.
        /// </summary>
        internal static string GOREDIT_TEXT_PICK_ALPHA {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_PICK_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-in: {0}.
        /// </summary>
        internal static string GOREDIT_TEXT_PLUG_IN {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_PLUG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-in location.
        /// </summary>
        internal static string GOREDIT_TEXT_PLUG_IN_LOCATION {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_PLUG_IN_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-in preferences.
        /// </summary>
        internal static string GOREDIT_TEXT_PLUGIN_PREFS {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_PLUGIN_PREFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-ins.
        /// </summary>
        internal static string GOREDIT_TEXT_PLUGINS {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string GOREDIT_TEXT_PREFERENCES {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string GOREDIT_TEXT_PROPERTIES {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string GOREDIT_TEXT_REASON {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string GOREDIT_TEXT_SAVING {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string GOREDIT_TEXT_SCANNING {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SCANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch area location.
        /// </summary>
        internal static string GOREDIT_TEXT_SCRATCH_LOCATION {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SCRATCH_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string GOREDIT_TEXT_SEARCH {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files were found for the search &apos;{0}&apos;.
        /// </summary>
        internal static string GOREDIT_TEXT_SEARCH_NO_FILES {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SEARCH_NO_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files returned from the search (hit ESC to go back).
        /// </summary>
        internal static string GOREDIT_TEXT_SEARCH_RESULTS {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SEARCH_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a color....
        /// </summary>
        internal static string GOREDIT_TEXT_SELECT_COLOR {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SELECT_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory to export the files into..
        /// </summary>
        internal static string GOREDIT_TEXT_SELECT_DIR_EXPORT {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SELECT_DIR_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        internal static string GOREDIT_TEXT_SELECT_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SELECT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string GOREDIT_TEXT_SIZE {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail view.
        /// </summary>
        internal static string GOREDIT_TEXT_THUMBNAIL_VIEW {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_THUMBNAIL_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string GOREDIT_TEXT_TYPE {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file.
        /// </summary>
        internal static string GOREDIT_TEXT_UNKNOWN_FILE {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_UNKNOWN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string GOREDIT_TEXT_UNTITLED {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_UNTITLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string GOREDIT_TEXT_VALUE {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string GOREDIT_TEXT_ZOOM {
            get {
                return ResourceManager.GetString("GOREDIT_TEXT_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the default image editor used by other plug-ins in 
        ///the editor.
        ///
        ///Changing this value will require any open content be closed 
        ///and re-opened to use the new image editor..
        /// </summary>
        internal static string GOREDIT_TIP_IMAGE_EDITOR {
            get {
                return ResourceManager.GetString("GOREDIT_TIP_IMAGE_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the directory that contains the plug-ins to use with 
        ///the editor.
        ///
        ///Changing this value will require a restart of the application..
        /// </summary>
        internal static string GOREDIT_TIP_PLUG_IN_LOCATION {
            get {
                return ResourceManager.GetString("GOREDIT_TIP_PLUG_IN_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages plug-ins that are responsible for creating/editing 
        ///specific types of content.
        ///
        ///To enable a plug-in, right click on the plug-in and select 
        ///&quot;Enable plug-in&quot;.
        ///
        ///To disable a plug-in, right click on the plug-in and select 
        ///&quot;Disable plug-in&quot;.
        ///
        ///To see why a plug-in failed to load, click on the failed tab 
        ///and double click on the plug-in item in the list..
        /// </summary>
        internal static string GOREDIT_TIP_PLUGINS {
            get {
                return ResourceManager.GetString("GOREDIT_TIP_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects a new working directory for the temporary files used 
        ///by content in the editor.
        ///
        ///Changing this value will require a restart of the application..
        /// </summary>
        internal static string GOREDIT_TIP_SCRATCH_LOCATION {
            get {
                return ResourceManager.GetString("GOREDIT_TIP_SCRATCH_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0} - {1}.
        /// </summary>
        internal static string GOREDIT_VERSION {
            get {
                return ResourceManager.GetString("GOREDIT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gorgon_2_Logo_Full {
            get {
                object obj = ResourceManager.GetObject("Gorgon_2_Logo_Full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gorgon_2_x_Logo_Blurry {
            get {
                object obj = ResourceManager.GetObject("Gorgon_2_x_Logo_Blurry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_missing_128x128 {
            get {
                object obj = ResourceManager.GetObject("image_missing_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_missing_16x16 {
            get {
                object obj = ResourceManager.GetObject("image_missing_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_16x16 {
            get {
                object obj = ResourceManager.GetObject("info_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linked_file_8x8 {
            get {
                object obj = ResourceManager.GetObject("linked_file_8x8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_item_16x16 {
            get {
                object obj = ResourceManager.GetObject("new_item_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok_16x16 {
            get {
                object obj = ResourceManager.GetObject("ok_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap project_node_16x16 {
            get {
                object obj = ResourceManager.GetObject("project_node_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string PROP_CATEGORY_APPEARANCE {
            get {
                return ResourceManager.GetString("PROP_CATEGORY_APPEARANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string PROP_CATEGORY_BEHAVIOR {
            get {
                return ResourceManager.GetString("PROP_CATEGORY_BEHAVIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string PROP_CATEGORY_DATA {
            get {
                return ResourceManager.GetString("PROP_CATEGORY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string PROP_CATEGORY_DESIGN {
            get {
                return ResourceManager.GetString("PROP_CATEGORY_DESIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the value for the cue text on the textbox.  Cue text is used to indicate what type of text is expected to be received by the textbox..
        /// </summary>
        internal static string PROP_CUETEXT_DESC {
            get {
                return ResourceManager.GetString("PROP_CUETEXT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the default extension to use when filtering the file list for the dialog and returns the selected filter when the dialog closes..
        /// </summary>
        internal static string PROP_DEFAULTEXTENSION_DESC {
            get {
                return ResourceManager.GetString("PROP_DEFAULTEXTENSION_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the default selected filename or the last selected file name..
        /// </summary>
        internal static string PROP_FILENAME_DESC {
            get {
                return ResourceManager.GetString("PROP_FILENAME_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view used for the file dialog..
        /// </summary>
        internal static string PROP_FILEVIEW_DESC {
            get {
                return ResourceManager.GetString("PROP_FILEVIEW_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether multiple files can be selected or not..
        /// </summary>
        internal static string PROP_MULTISELECT_DESC {
            get {
                return ResourceManager.GetString("PROP_MULTISELECT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides a name for the content.  The name should conform to a standard file name..
        /// </summary>
        internal static string PROP_NAME_DESC {
            get {
                return ResourceManager.GetString("PROP_NAME_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial directory for the file dialog..
        /// </summary>
        internal static string PROP_STARTDIRECTORY_DESC {
            get {
                return ResourceManager.GetString("PROP_STARTDIRECTORY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows or hides the caption for the content panel..
        /// </summary>
        internal static string PROP_TEXT_CAPTION_VISIBLE_DESC {
            get {
                return ResourceManager.GetString("PROP_TEXT_CAPTION_VISIBLE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the text for the caption on the content panel control..
        /// </summary>
        internal static string PROP_TEXT_CONTENT_PANEL_DESC {
            get {
                return ResourceManager.GetString("PROP_TEXT_CONTENT_PANEL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the text value to assign to the caption of the window..
        /// </summary>
        internal static string PROP_TEXT_DESC {
            get {
                return ResourceManager.GetString("PROP_TEXT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the text to display on the tab for the preference panel..
        /// </summary>
        internal static string PROP_TEXT_PREF_PANEL_DESC {
            get {
                return ResourceManager.GetString("PROP_TEXT_PREF_PANEL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PropertyChecker {
            get {
                object obj = ResourceManager.GetObject("PropertyChecker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove_16x16 {
            get {
                object obj = ResourceManager.GetObject("remove_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_collapse_16x16 {
            get {
                object obj = ResourceManager.GetObject("tree_collapse_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_expand_16x16 {
            get {
                object obj = ResourceManager.GetObject("tree_expand_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown_document_16x16 {
            get {
                object obj = ResourceManager.GetObject("unknown_document_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_16x16 {
            get {
                object obj = ResourceManager.GetObject("up_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
