
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'FormMain' contains field '_image' that is of IDisposable type 'Image', but it is never disposed. Change the Dispose method on 'FormMain' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.FormMain._image")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'FormMain' contains field '_instructions' that is of IDisposable type 'Label', but it is never disposed. Change the Dispose method on 'FormMain' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.FormMain._instructions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'FormMain' contains field '_picture' that is of IDisposable type 'PictureBox', but it is never disposed. Change the Dispose method on 'FormMain' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.FormMain._picture")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'FormMain' contains field '_textDisplay' that is of IDisposable type 'TextBox', but it is never disposed. Change the Dispose method on 'FormMain' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.FormMain._textDisplay")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'FormMain' contains field '_textFont' that is of IDisposable type 'Font', but it is never disposed. Change the Dispose method on 'FormMain' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.FormMain._textFont")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'OnFormClosing' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.FormMain.OnFormClosing(System.Windows.Forms.FormClosingEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'OnLoad' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.FormMain.OnLoad(System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'TreeFileSystem_BeforeCollapse' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.FormMain.TreeFileSystem_BeforeCollapse(System.Object,System.Windows.Forms.TreeViewCancelEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'TreeFileSystem_BeforeExpand' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.FormMain.TreeFileSystem_BeforeExpand(System.Object,System.Windows.Forms.TreeViewCancelEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'TreeFileSystem_NodeMouseDoubleClick' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.FormMain.TreeFileSystem_NodeMouseDoubleClick(System.Object,System.Windows.Forms.TreeNodeMouseClickEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1304:The behavior of 'string.ToLower()' could vary based on the current user's locale settings. Replace this call in 'FormMain.TreeFileSystem_NodeMouseDoubleClick(object, TreeNodeMouseClickEventArgs)' with a call to 'string.ToLower(CultureInfo)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.FormMain.TreeFileSystem_NodeMouseDoubleClick(System.Object,System.Windows.Forms.TreeNodeMouseClickEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'char.ToString()' could vary based on the current user's locale settings. Replace this call in 'Program.GetResourcePath(string)' with a call to 'char.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.Program.GetResourcePath(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.EndsWith(string)' could vary based on the current user's locale settings. Replace this call in 'Gorgon.Examples.Program.GetResourcePath(string)' with a call to 'string.EndsWith(string, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.Program.GetResourcePath(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Main' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.Program.Main")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'char.ToString()' could vary based on the current user's locale settings. Replace this call in 'Program.PlugInPath.get' with a call to 'char.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~P:Gorgon.Examples.Program.PlugInPath")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.EndsWith(string)' could vary based on the current user's locale settings. Replace this call in 'Gorgon.Examples.Program.PlugInPath.get' with a call to 'string.EndsWith(string, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~P:Gorgon.Examples.Program.PlugInPath")]