// Gorgon.
// Copyright (C) 2025 Michael Winsor
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
// 
// Created: January 11, 2025 1:40:16 AM
//

using Gorgon.Native;
using Gorgon.Windows.Input.Properties;

namespace Gorgon.Windows.Input;

/// <summary>
/// Values to indentify what kind of event data is stored in the <see cref="GorgonInputEvent"/> structure.
/// </summary>
public enum GorgonInputDeviceType
{
    /// <summary>
    /// No device type.
    /// </summary>
    None = 0,
    /// <summary>
    /// The keyboard generated this event.
    /// </summary>
    Keyboard = 1,
    /// <summary>
    /// The mouse generated this event.
    /// </summary>
    Mouse = 2,
    /// <summary>
    /// A human interface device (HID) generated this event.
    /// </summary>
    HumanInterfaceDevice = 3
}

/// <summary>
/// An event that is generated by data coming in to the input system.
/// </summary>
public class GorgonInputEvent
{
    // The internal raw input report data.
    private RAWINPUT _rawInputData;

    public int MX => _rawInputData.Union.Mouse.LastX;
    public int MY => _rawInputData.Union.Mouse.LastY;

    /// <summary>
    /// Property to return the type of the device that generated the event.
    /// </summary>
    public GorgonInputDeviceType DeviceType
    {
        get;
        private set;
    }

    /// <summary>
    /// Property to return the handle to the device that generated the event.
    /// </summary>
    public nint DeviceHandle
    {
        get;
        private set;
    }

    /// <summary>
    /// Property to return the timestamp, in microseconds, for the event.
    /// </summary>
    public long TimeStamp
    {
        get;
        private set;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GorgonInputEvent"/> struct from raw input data.
    /// </summary>
    /// <param name="data">The raw input data to translate.</param>
    /// <param name="timeStamp">The timestamp for the event.</param>
    internal void FromRawInput(ref readonly RAWINPUT data, long timeStamp)
    {
        DeviceType = data.Header.Type switch
        {
            RawInputType.Keyboard => GorgonInputDeviceType.Keyboard,
            RawInputType.Mouse => GorgonInputDeviceType.Mouse,
            RawInputType.HID => GorgonInputDeviceType.HumanInterfaceDevice,
            _ => throw new ArgumentException(string.Format(Resources.GORINP_RAW_ERR_UNKNOWN_DEVICE_TYPE, data.Header.Type), nameof(data))
        };
        DeviceHandle = data.Header.Device;        
        TimeStamp = timeStamp;
        _rawInputData = data;
    }
}
