// Gorgon.
// Copyright (C) 2025 Michael Winsor
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
// 
// Created: January 11, 2025 1:40:16 AM
//

using System.Diagnostics;
using System.Numerics;
using System.Runtime.CompilerServices;
using Gorgon.Input.Devices;
using Windows.Win32.Foundation;
using Windows.Win32.UI.Input;

namespace Gorgon.Input;

/// <summary>
/// An event that is generated by data coming in to the input system.
/// </summary>
public class GorgonInputEvent
{
    // The internal raw input report data for a mouse.
    private RawMouseData _rawInputMouseState;

    // The internal raw input report data for a keyboard.   
    private RawKeyboardData _rawInputKeyboardState;

    // The buffers for the HID report data.
    private byte[] _hidReport = [];

    // The HID report data size.
    private int _hidReportSize = 0;

    /// <summary>
    /// An empty event.
    /// </summary>
    public static readonly GorgonInputEvent Empty = new();

    /// <summary>
    /// Property to return a reference to the internal raw input mouse data contained within this event.
    /// </summary>
    internal ref readonly RawMouseData RawInputMouseData => ref _rawInputMouseState;

    /// <summary>
    /// Property to return a reference to the internal raw input keyboard data contained within this event.
    /// </summary>
    internal ref readonly RawKeyboardData RawInputKeyboardData => ref _rawInputKeyboardState;

    /// <summary>
    /// Property to return a reference to the internal raw input HID report data contained within this event.
    /// </summary>
    internal ReadOnlySpan<byte> RawInputHidReport => _hidReport.AsSpan(0, _hidReportSize);

    /// <summary>
    /// Property to return the preparsed data for the device.
    /// </summary>
    internal byte[] PreparsedData
    {
        get;
        private set;
    } = [];

    /// <summary>
    /// Property to return the number of data items in a report.
    /// </summary>
    internal int HidDataLength
    {
        get;
        private set;
    }

    /// <summary>
    /// Property to return the HID button indices.
    /// </summary>
    internal ushort[] HidButtonIndices
    {
        get;
        private set;
    } = [];

    /// <summary>
    /// Property to return HID hat switch indices.
    /// </summary>
    internal PovMap[] HidHatSwitchIndices
    {
        get;
        private set;
    } = [];

    /// <summary>
    /// Property to return the type of the device that generated the event.
    /// </summary>
    public InputDeviceType DeviceType
    {
        get;
        private set;
    }

    /// <summary>
    /// Property to return the handle to the device that generated the event.
    /// </summary>
    public nint DeviceHandle
    {
        get;
        private set;
    }

    /// <summary>
    /// Property to return the timestamp, in microseconds, for the event.
    /// </summary>
    public long TimeStamp
    {
        get;
        private set;
    }

    /// <summary>
    /// Function to reset the input event state.
    /// </summary>
    internal void Reset()
    {
        DeviceType = InputDeviceType.None;
        DeviceHandle = IntPtr.Zero;
        TimeStamp = 0;
        _rawInputMouseState = default;
        _rawInputKeyboardState = default;
        _hidReportSize = 0;
        PreparsedData = [];
        HidButtonIndices = [];
        HidHatSwitchIndices = [];
    }

    /// <summary>
    /// Function to copy data to another input event.
    /// </summary>
    /// <param name="dest">The input event to copy into.</param>
    internal void CopyTo(GorgonInputEvent dest)
    {
        dest.HidDataLength = HidDataLength;
        dest._hidReportSize = _hidReportSize;
        dest._rawInputMouseState = _rawInputMouseState;
        dest._rawInputKeyboardState = _rawInputKeyboardState;
        dest.DeviceHandle = DeviceHandle;
        dest.DeviceType = DeviceType;
        dest.TimeStamp = TimeStamp;

        if (DeviceType != InputDeviceType.GamingDevice)
        {
            return;
        }

        dest.PreparsedData = PreparsedData;
        dest.HidButtonIndices = HidButtonIndices;
        dest.HidHatSwitchIndices = HidHatSwitchIndices;

        if (_hidReport.Length > dest._hidReport.Length)
        {
            dest._hidReport = new byte[_hidReport.Length];
        }

        Array.Copy(_hidReport, dest._hidReport, dest._hidReportSize);
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GorgonInputEvent"/> struct from raw input data.
    /// </summary>
    /// <param name="handle">The device handle.</param>
    /// <param name="data">The raw input data to translate.</param>
    /// <param name="deviceInfo">The device information.</param>
    /// <param name="timeStamp">The timestamp for the event.</param>
    internal void FromRawInput(HANDLE handle, ref readonly RAWHID data, GamingDeviceInfo deviceInfo, long timeStamp)
    {
        DeviceType = InputDeviceType.GamingDevice;
        DeviceHandle = handle;
        TimeStamp = timeStamp;
        _rawInputKeyboardState = default;
        _rawInputMouseState = default;
        HidDataLength = deviceInfo.HidDataLength;

        _hidReportSize = (int)(data.dwSizeHid * data.dwCount);

        Debug.Assert(_hidReportSize > 0, $"Buffer size {_hidReportSize} is not valid.");

        if (_hidReport.Length < _hidReportSize)
        {
            _hidReport = new byte[BitOperations.RoundUpToPowerOf2((uint)_hidReportSize)];
            Array.Clear(_hidReport);
        }

        ref readonly byte src = ref data.bRawData.e0;
        ref byte dest = ref _hidReport[0];

        Unsafe.CopyBlock(ref dest, in src, (uint)_hidReportSize);

        PreparsedData = deviceInfo.PreparsedData;
        HidButtonIndices = deviceInfo.ButtonMap;
        HidHatSwitchIndices = deviceInfo.PovMap;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GorgonInputEvent"/> struct from raw input data.
    /// </summary>
    /// <param name="handle">The device handle.</param>
    /// <param name="data">The raw input data to translate.</param>
    /// <param name="timeStamp">The timestamp for the event.</param>
    internal void FromRawInput(HANDLE handle, ref readonly RawMouseData data, long timeStamp)
    {
        DeviceType = InputDeviceType.Mouse;
        DeviceHandle = handle;
        TimeStamp = timeStamp;
        _rawInputKeyboardState = default;
        _rawInputMouseState = data;
        _hidReportSize = 0;
        PreparsedData = [];
        HidButtonIndices = [];
        HidHatSwitchIndices = [];
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GorgonInputEvent"/> struct from raw input data.
    /// </summary>
    /// <param name="handle">The device handle.</param>
    /// <param name="data">The raw input data to translate.</param>
    /// <param name="timeStamp">The timestamp for the event.</param>
    internal void FromRawInput(HANDLE handle, ref readonly RawKeyboardData data, long timeStamp)
    {
        DeviceType = InputDeviceType.Keyboard;
        DeviceHandle = handle;
        TimeStamp = timeStamp;
        _rawInputKeyboardState = data;
        _rawInputMouseState = default;
        _hidReportSize = 0;
        PreparsedData = [];
        HidButtonIndices = [];
        HidHatSwitchIndices = [];
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GorgonInputEvent"/> class.
    /// </summary>
    internal GorgonInputEvent()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GorgonInputEvent"/> class with a copy of an existing event.
    /// </summary>
    /// <param name="source">The event to copy.</param>
    public GorgonInputEvent(GorgonInputEvent source) => source.CopyTo(this);
}
