
// 
// Gorgon
// Copyright (C) 2020 Michael Winsor
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE
// 
// Created: June 28, 2020 6:20:59 PM
// 

using Gorgon.Editor.UI;

namespace Gorgon.Editor.AnimationEditor;

/// <summary>
/// The view model to interact with properties for an animation
/// </summary>
internal interface IProperties
    : IHostedPanelViewModel
{
    /// <summary>
    /// Property to set or return the length of the animation, in seconds.
    /// </summary>
    float Length
    {
        get;
        set;
    }

    /// <summary>
    /// Property to set or return the frames per second for the animation.
    /// </summary>
    float Fps
    {
        get;
        set;
    }

    /// <summary>
    /// Property to set or return whether the animation is looping or not.
    /// </summary>
    bool IsLooped
    {
        get;
        set;
    }

    /// <summary>
    /// Property to set or return the number of times the animation may loop.
    /// </summary>
    int LoopCount
    {
        get;
        set;
    }

    /// <summary>
    /// Property to return the number of keys generated by the length/fps.
    /// </summary>
    int KeyCount
    {
        get;
    }
}
