
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'Context' contains field '_splashScreen' that is of IDisposable type 'formSplash', but it is never disposed. Change the Dispose method on 'Context' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.Context._splashScreen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'formMain' contains field '_bitmap' that is of IDisposable type 'Bitmap', but it is never disposed. Change the Dispose method on 'formMain' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.formMain._bitmap")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'formMain' contains field '_formGraphics' that is of IDisposable type 'Graphics', but it is never disposed. Change the Dispose method on 'formMain' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.formMain._formGraphics")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'formMain' contains field '_graphics' that is of IDisposable type 'Graphics', but it is never disposed. Change the Dispose method on 'formMain' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Examples.formMain._graphics")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'RunMe' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.Context.RunMe")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'OnLoad' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.formMain.OnLoad(System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'OnSizeChanged' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.formMain.OnSizeChanged(System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'float.ToString(string)' could vary based on the current user's locale settings. Replace this call in 'Program.Idle()' with a call to 'float.ToString(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.Program.Idle~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Main' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.Program.Main")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'float.ToString(string)' could vary based on the current user's locale settings. Replace this call in 'Program.NewIdle()' with a call to 'float.ToString(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Examples.Program.NewIdle~System.Boolean")]