
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'MainForm' contains field '_2D' that is of IDisposable type 'Gorgon2D', but it is never disposed. Change the Dispose method on 'MainForm' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Input.Example.MainForm._2D")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'MainForm' contains field '_assemblyCache' that is of IDisposable type 'GorgonMefPlugInCache', but it is never disposed. Change the Dispose method on 'MainForm' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Input.Example.MainForm._assemblyCache")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'MainForm' contains field '_backBuffer' that is of IDisposable type 'GorgonRenderTarget2DView', but it is never disposed. Change the Dispose method on 'MainForm' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Input.Example.MainForm._backBuffer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'MainForm' contains field '_backBufferView' that is of IDisposable type 'GorgonTexture2DView', but it is never disposed. Change the Dispose method on 'MainForm' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Input.Example.MainForm._backBufferView")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'MainForm' contains field '_backupImage' that is of IDisposable type 'GorgonTexture2D', but it is never disposed. Change the Dispose method on 'MainForm' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Input.Example.MainForm._backupImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'MainForm' contains field '_font' that is of IDisposable type 'GorgonFont', but it is never disposed. Change the Dispose method on 'MainForm' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Input.Example.MainForm._font")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'MainForm' contains field '_graphics' that is of IDisposable type 'GorgonGraphics', but it is never disposed. Change the Dispose method on 'MainForm' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Input.Example.MainForm._graphics")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'MainForm' contains field '_input' that is of IDisposable type 'GorgonRawInput', but it is never disposed. Change the Dispose method on 'MainForm' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Input.Example.MainForm._input")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'MainForm' contains field '_screen' that is of IDisposable type 'GorgonSwapChain', but it is never disposed. Change the Dispose method on 'MainForm' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:Gorgon.Input.Example.MainForm._screen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'OnLoad' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Input.Example.MainForm.OnLoad(System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Main' to catch a more specific exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Gorgon.Input.Example.Program.Main")]